import type { CurriculumModule, Grade } from "@/types";

// Compact rendering of the Spotlight 2-8 grade curriculum.
// Source: Express Publishing / «Просвещение» Spotlight textbook series. Approximate.
// Vocabulary lists are deliberately wide — see src/lib/vocabulary.ts for the
// translations dictionary; modules link to it via the lemma strings below.
export const CURRICULUM: CurriculumModule[] = [
  // === Grade 2 ===
  {
    id: "g2-m1",
    grade: 2,
    number: 1,
    title: "My Home",
    topics: ["Дом и комната", "Мебель", "Члены семьи"],
    grammar: ["Глагол to be (am/is/are)", "This is / These are", "Артикли a/an/the"],
    vocabulary: [
      "bedroom", "kitchen", "bathroom", "garden", "dining room",
      "living room", "hall", "stairs", "door", "window",
      "roof", "chair", "table", "bed", "sofa",
      "lamp", "TV", "clock", "picture", "carpet",
    ],
  },
  {
    id: "g2-m2",
    grade: 2,
    number: 2,
    title: "My Birthday",
    topics: ["День рождения", "Цифры 1-10", "Любимая еда"],
    grammar: ["How many …?", "I like / I don't like", "Множественное число существительных"],
    vocabulary: [
      "cake", "candles", "ice cream", "chocolate", "lemonade",
      "balloon", "present", "party", "friend", "song",
      "dance", "happy", "year", "old", "number",
      "one", "two", "three", "four", "five",
    ],
  },
  {
    id: "g2-m3",
    grade: 2,
    number: 3,
    title: "My Animals",
    topics: ["Любимые животные", "Способности", "Глаголы движения"],
    grammar: ["Can / can't для способностей", "Have got / has got"],
    vocabulary: [
      "fish", "bird", "frog", "horse", "chimp",
      "dog", "cat", "rabbit", "mouse", "hen",
      "cow", "sheep", "pig", "duck", "swan",
      "jump", "swim", "fly", "run", "climb",
    ],
  },
  {
    id: "g2-m4",
    grade: 2,
    number: 4,
    title: "My Toys",
    topics: ["Игрушки", "Предлоги места", "Цвета"],
    grammar: ["Предлоги (in, on, under, behind, near)", "Множественное число (-s, -es)"],
    vocabulary: [
      "teddy bear", "toy soldier", "ballerina", "shelf", "musical box",
      "doll", "ball", "kite", "drum", "puzzle",
      "robot", "car", "bike", "plane", "train",
      "in", "on", "under", "behind", "near",
    ],
  },

  // === Grade 3 ===
  {
    id: "g3-m1",
    grade: 3,
    number: 1,
    title: "School Days",
    topics: ["Школьные предметы", "Расписание", "Школьные принадлежности"],
    grammar: ["Present Simple (утверждение)", "Команды (Imperative)", "Дни недели"],
    vocabulary: [
      "Maths", "English", "PE", "Science", "Art",
      "Music", "History", "Geography", "Russian", "IT",
      "lesson", "class", "pupil", "teacher", "school",
      "book", "pen", "pencil", "ruler", "rubber",
    ],
  },
  {
    id: "g3-m2",
    grade: 3,
    number: 2,
    title: "Family Moments",
    topics: ["Семья", "Чувства и эмоции"],
    grammar: ["Possessive adjectives (my, your, his, her)", "Who is this?"],
    vocabulary: [
      "grandma", "grandpa", "cousin", "uncle", "aunt",
      "mum", "dad", "sister", "brother", "parent",
      "baby", "family", "photo", "love", "hug",
      "kiss", "son", "daughter", "wife", "husband",
    ],
  },
  {
    id: "g3-m3",
    grade: 3,
    number: 3,
    title: "All the Things I Like!",
    topics: ["Еда и напитки", "Предпочтения", "За столом"],
    grammar: ["Present Simple (вопросы и отрицания)", "Some / any"],
    vocabulary: [
      "pasta", "rice", "meat", "fish", "vegetables",
      "fruit", "apple", "banana", "orange", "tomato",
      "potato", "sandwich", "soup", "salad", "pizza",
      "milk", "juice", "water", "tea", "coffee",
    ],
  },
  {
    id: "g3-m4",
    grade: 3,
    number: 4,
    title: "Come In and Play!",
    topics: ["Игрушки дома", "Комнаты", "Совместные игры"],
    grammar: ["There is / there are", "Whose is it?"],
    vocabulary: [
      "doll", "plane", "train", "musical box", "rocking horse",
      "computer", "phone", "camera", "book", "magazine",
      "board game", "card", "dice", "chess", "lego",
      "toy", "game", "room", "play", "fun",
    ],
  },

  // === Grade 4 ===
  {
    id: "g4-m1",
    grade: 4,
    number: 1,
    title: "Back Together",
    topics: ["Внешность", "Друзья", "Эмоции"],
    grammar: ["Present Simple (повторение)", "Вопросы What / Who / Where", "Описание людей"],
    vocabulary: [
      "tall", "short", "funny", "kind", "shy",
      "friendly", "happy", "sad", "angry", "tired",
      "hair", "eyes", "nose", "mouth", "face",
      "smile", "laugh", "talk", "listen", "friend",
    ],
  },
  {
    id: "g4-m2",
    grade: 4,
    number: 2,
    title: "Working Day",
    topics: ["Профессии", "Время суток", "Места работы"],
    grammar: ["Present Simple (3-е лицо -s/-es)", "Наречия частотности"],
    vocabulary: [
      "doctor", "dentist", "farmer", "waiter", "mechanic",
      "nurse", "teacher", "pilot", "postman", "baker",
      "vet", "fireman", "policeman", "driver", "cleaner",
      "work", "job", "hospital", "restaurant", "factory",
    ],
  },
  {
    id: "g4-m3",
    grade: 4,
    number: 3,
    title: "Tasty Treats",
    topics: ["Еда на кухне", "Рецепты", "Покупки в магазине"],
    grammar: ["Much / many / a lot of", "A cup of / a glass of"],
    vocabulary: [
      "bread", "butter", "cheese", "honey", "lemonade",
      "cereal", "jam", "biscuit", "sweet", "chocolate",
      "sugar", "salt", "pepper", "oil", "flour",
      "egg", "lemon", "strawberry", "grape", "melon",
    ],
  },
  {
    id: "g4-m4",
    grade: 4,
    number: 4,
    title: "At the Zoo",
    topics: ["Животные в зоопарке", "Характер", "Среда обитания"],
    grammar: ["Present Continuous", "Сравнение Present Simple и Continuous"],
    vocabulary: [
      "lion", "elephant", "giraffe", "peacock", "seal",
      "tiger", "monkey", "bear", "kangaroo", "zebra",
      "panda", "crocodile", "snake", "parrot", "eagle",
      "wing", "paw", "tail", "fur", "feather",
    ],
  },

  // === Grade 5 ===
  {
    id: "g5-m1",
    grade: 5,
    number: 1,
    title: "School Days",
    topics: ["Школа", "Расписание", "Школьная жизнь"],
    grammar: ["Present Simple", "Глаголы состояния"],
    vocabulary: [
      "timetable", "schoolbag", "pupil", "headmaster", "subject",
      "term", "break", "library", "gym", "canteen",
      "uniform", "lesson", "homework", "exam", "mark",
      "classroom", "blackboard", "chalk", "desk", "locker",
    ],
  },
  {
    id: "g5-m2",
    grade: 5,
    number: 2,
    title: "That's Me!",
    topics: ["Личная информация", "Страны", "Национальности"],
    grammar: ["Have got / has got", "Possessive case ('s, of)"],
    vocabulary: [
      "Russia", "Britain", "Spain", "passport", "nationality",
      "France", "Germany", "Italy", "USA", "Canada",
      "British", "French", "German", "Italian", "language",
      "country", "capital", "flag", "citizen",
    ],
  },
  {
    id: "g5-m3",
    grade: 5,
    number: 3,
    title: "My Home, My Castle",
    topics: ["Дом", "Мебель", "Бытовая техника"],
    grammar: ["There is / there are", "Предлоги места"],
    vocabulary: [
      "armchair", "carpet", "fridge", "mirror", "wardrobe",
      "sofa", "cushion", "bookcase", "desk", "lamp",
      "curtains", "painting", "vase", "bath", "shower",
      "sink", "oven", "cooker", "dishwasher", "washing machine",
    ],
  },
  {
    id: "g5-m4",
    grade: 5,
    number: 4,
    title: "Family Ties",
    topics: ["Семья", "Описание людей", "Отношения"],
    grammar: ["Object pronouns", "Can / can't"],
    vocabulary: [
      "brave", "clever", "kind", "noisy", "patient",
      "lazy", "helpful", "polite", "rude", "honest",
      "twin", "only child", "niece", "nephew", "stepfather",
      "stepmother", "grandparent", "relative", "cousin", "family tree",
    ],
  },

  // === Grade 6 ===
  {
    id: "g6-m1",
    grade: 6,
    number: 1,
    title: "Who's Who?",
    topics: ["Знакомства", "Документы", "Контактные данные"],
    grammar: ["Have got / Has got", "Question words"],
    vocabulary: [
      "ID card", "nickname", "address", "postcode", "signature",
      "age", "birthday", "hobby", "contact", "email",
      "phone number", "full name", "surname", "first name", "middle name",
      "country", "city", "street", "house", "flat",
    ],
  },
  {
    id: "g6-m2",
    grade: 6,
    number: 2,
    title: "Here We Are",
    topics: ["Время", "Месяцы и даты", "Праздники"],
    grammar: ["Предлоги времени (at/in/on)", "Ordinal numbers"],
    vocabulary: [
      "calendar", "celebration", "month", "season", "festival",
      "weekday", "weekend", "holiday", "anniversary", "ceremony",
      "January", "February", "March", "July", "autumn",
      "summer", "winter", "spring", "century", "decade",
    ],
  },
  {
    id: "g6-m3",
    grade: 6,
    number: 3,
    title: "Getting Around",
    topics: ["Транспорт", "Дорожные знаки", "Путешествия"],
    grammar: ["Imperative", "Can / must"],
    vocabulary: [
      "bicycle", "underground", "helicopter", "tram", "motorbike",
      "bus", "car", "train", "plane", "ferry",
      "taxi", "ship", "boat", "lorry", "van",
      "station", "airport", "port", "road", "traffic light",
    ],
  },
  {
    id: "g6-m4",
    grade: 6,
    number: 4,
    title: "Day After Day",
    topics: ["Распорядок дня", "Свободное время", "Привычки"],
    grammar: ["Present Simple", "Наречия частотности"],
    vocabulary: [
      "routine", "spare time", "hobby", "weekend", "habit",
      "alarm clock", "breakfast", "lunch", "dinner", "bath",
      "brush", "dress", "sleep", "wake up", "get up",
      "go to bed", "daily", "often", "sometimes",
    ],
  },

  // === Grade 7 ===
  {
    id: "g7-m1",
    grade: 7,
    number: 1,
    title: "Lifestyles",
    topics: ["Город и деревня", "Образ жизни", "Окружение"],
    grammar: ["Present Simple vs Present Continuous"],
    vocabulary: [
      "countryside", "suburbs", "skyscraper", "cottage", "flat",
      "neighborhood", "downtown", "village", "town", "city",
      "urban", "rural", "busy", "quiet", "peaceful",
      "crowded", "polluted", "traffic", "building", "neighbour",
    ],
  },
  {
    id: "g7-m2",
    grade: 7,
    number: 2,
    title: "Tale Time",
    topics: ["Литература", "Истории", "Жанры"],
    grammar: ["Past Simple (правильные/неправильные глаголы)"],
    vocabulary: [
      "character", "plot", "hero", "villain", "adventure",
      "fairy tale", "novel", "poem", "legend", "myth",
      "fiction", "non-fiction", "narrator", "dialogue", "scene",
      "chapter", "page", "library", "author", "title",
    ],
  },
  {
    id: "g7-m3",
    grade: 7,
    number: 3,
    title: "Profiles",
    topics: ["Черты характера", "Знаменитости", "Биографии"],
    grammar: ["Относительные местоимения (who, which, that)"],
    vocabulary: [
      "ambitious", "creative", "patient", "loyal", "generous",
      "hard-working", "talented", "gifted", "confident", "modest",
      "humble", "optimistic", "pessimistic", "energetic", "lazy",
      "reliable", "stubborn", "strict", "friendly", "sensitive",
    ],
  },
  {
    id: "g7-m4",
    grade: 7,
    number: 4,
    title: "In the News",
    topics: ["СМИ", "Новости", "Журналистика"],
    grammar: ["Past Continuous", "Past Simple vs Past Continuous"],
    vocabulary: [
      "headline", "broadcast", "journalist", "report", "article",
      "news", "weather", "interview", "magazine", "newspaper",
      "channel", "anchor", "microphone", "camera", "studio",
      "breaking news", "gossip", "scandal", "story", "source",
    ],
  },

  // === Grade 8 ===
  {
    id: "g8-m1",
    grade: 8,
    number: 1,
    title: "Socialising",
    topics: ["Общение", "Первое впечатление", "Этикет"],
    grammar: ["Present Simple / Continuous / Perfect"],
    vocabulary: [
      "polite", "rude", "sociable", "outgoing", "introvert",
      "extrovert", "friendly", "unfriendly", "formal", "informal",
      "manners", "etiquette", "greeting", "smile", "handshake",
      "gesture", "body language", "conversation", "small talk", "communication",
    ],
  },
  {
    id: "g8-m2",
    grade: 8,
    number: 2,
    title: "Food & Shopping",
    topics: ["Магазины", "Деньги", "Покупки"],
    grammar: ["Past Simple / Present Perfect"],
    vocabulary: [
      "receipt", "discount", "refund", "grocery", "boutique",
      "supermarket", "mall", "market", "cashier", "shop assistant",
      "customer", "brand", "label", "price", "sale",
      "bargain", "queue", "basket", "trolley", "change",
    ],
  },
  {
    id: "g8-m3",
    grade: 8,
    number: 3,
    title: "Great Minds",
    topics: ["Знаменитые учёные", "Изобретения", "Открытия"],
    grammar: ["Past Perfect", "Used to / would"],
    vocabulary: [
      "invention", "discover", "genius", "breakthrough", "experiment",
      "scientist", "inventor", "philosopher", "mathematician", "physicist",
      "chemist", "theory", "formula", "laboratory", "microscope",
      "telescope", "technology", "research", "knowledge", "evidence",
    ],
  },
  {
    id: "g8-m4",
    grade: 8,
    number: 4,
    title: "Be Yourself",
    topics: ["Внешность и стиль", "Мода", "Одежда"],
    grammar: ["Модальные глаголы: must / can't / may"],
    vocabulary: [
      "outfit", "trendy", "baggy", "tight", "formal",
      "casual", "elegant", "stylish", "fashionable", "jeans",
      "jacket", "scarf", "gloves", "boots", "sneakers",
      "dress", "suit", "shirt", "t-shirt", "design",
    ],
  },

  // === Extension modules 5–8 (по 4 на класс — добивают расписание УМК
  // Spotlight, у которого реально 8–10 модулей на класс). ===

  // Grade 2 · Modules 5–8
  {
    id: "g2-m5",
    grade: 2,
    number: 5,
    title: "My Holidays",
    topics: ["Времена года", "Погода", "Каникулы"],
    grammar: ["It is + adjective", "Be wearing"],
    vocabulary: [
      "summer", "winter", "spring", "autumn", "sunny",
      "rainy", "snowy", "cloudy", "windy", "hot",
      "cold", "warm", "season", "weather", "umbrella",
      "raincoat", "boots", "sandals", "hat", "scarf",
    ],
  },
  {
    id: "g2-m6",
    grade: 2,
    number: 6,
    title: "Food I Like",
    topics: ["Любимая еда", "Завтрак и обед", "Фрукты"],
    grammar: ["I like / I don't like + noun", "Артикли the"],
    vocabulary: [
      "milk", "bread", "honey", "cheese", "egg",
      "porridge", "yoghurt", "biscuit", "cookie", "jam",
      "butter", "salt", "sugar", "pepper", "rice",
      "fish", "meat", "soup", "salad", "fruit",
    ],
  },
  {
    id: "g2-m7",
    grade: 2,
    number: 7,
    title: "My Body",
    topics: ["Части тела", "Здоровье", "Эмоции"],
    grammar: ["I have got + noun", "My / your"],
    vocabulary: [
      "head", "hair", "eyes", "ears", "nose",
      "mouth", "teeth", "lips", "tongue", "neck",
      "shoulder", "arm", "elbow", "hand", "finger",
      "leg", "knee", "foot", "toe", "back",
    ],
  },
  {
    id: "g2-m8",
    grade: 2,
    number: 8,
    title: "Going Places",
    topics: ["Транспорт", "Город", "Путешествия"],
    grammar: ["Let's + verb", "By bus / by car"],
    vocabulary: [
      "bus", "car", "bike", "plane", "train",
      "boat", "ship", "taxi", "tram", "underground",
      "park", "shop", "school", "library", "museum",
      "zoo", "stadium", "cinema", "cafe", "playground",
    ],
  },

  // Grade 3 · Modules 5–8
  {
    id: "g3-m5",
    grade: 3,
    number: 5,
    title: "Furry Friends",
    topics: ["Животные", "Зоопарк", "Описание"],
    grammar: ["Has got / Have got", "Множественное число (irregular)"],
    vocabulary: [
      "elephant", "lion", "tiger", "monkey", "giraffe",
      "zebra", "bear", "kangaroo", "panda", "crocodile",
      "snake", "spider", "fox", "wolf", "deer",
      "owl", "eagle", "parrot", "dolphin", "whale",
    ],
  },
  {
    id: "g3-m6",
    grade: 3,
    number: 6,
    title: "Home Sweet Home",
    topics: ["Дом", "Мебель", "Описание комнат"],
    grammar: ["Предлоги места", "There is / there are"],
    vocabulary: [
      "fridge", "cooker", "sink", "shower", "mirror",
      "lamp", "carpet", "curtain", "wardrobe", "shelf",
      "armchair", "cupboard", "drawer", "ceiling", "floor",
      "wall", "bath", "fireplace", "vase", "blanket",
    ],
  },
  {
    id: "g3-m7",
    grade: 3,
    number: 7,
    title: "A Day Off",
    topics: ["Распорядок дня", "Свободное время", "Профессии"],
    grammar: ["Present Simple (3 лицо)", "Adverbs of frequency"],
    vocabulary: [
      "doctor", "nurse", "teacher", "driver", "farmer",
      "vet", "pilot", "builder", "cook", "dancer",
      "singer", "actor", "writer", "painter", "musician",
      "always", "usually", "often", "sometimes", "never",
    ],
  },
  {
    id: "g3-m8",
    grade: 3,
    number: 8,
    title: "Day by Day",
    topics: ["Дни недели", "Часы и время", "Погода"],
    grammar: ["What time is it?", "On Monday / at 7 o'clock"],
    vocabulary: [
      "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
      "Saturday", "Sunday", "morning", "afternoon", "evening",
      "night", "midnight", "noon", "today", "tomorrow",
      "yesterday", "early", "late", "minute", "hour",
    ],
  },

  // Grade 4 · Modules 5–8
  {
    id: "g4-m5",
    grade: 4,
    number: 5,
    title: "Where Were You Yesterday?",
    topics: ["Прошлое", "Воспоминания", "Места"],
    grammar: ["Past Simple глагола to be", "Yes/No вопросы в Past Simple"],
    vocabulary: [
      "yesterday", "last week", "last year", "ago", "then",
      "before", "after", "during", "at home", "at school",
      "at the park", "at the beach", "at the cinema", "at the zoo", "shopping",
      "happy", "sad", "tired", "bored", "excited",
    ],
  },
  {
    id: "g4-m6",
    grade: 4,
    number: 6,
    title: "Tell the Tale",
    topics: ["Сказки", "Литература", "Действия в прошлом"],
    grammar: ["Past Simple (regular & irregular)", "Linking words: then, after that"],
    vocabulary: [
      "princess", "prince", "king", "queen", "wizard",
      "witch", "fairy", "dragon", "castle", "forest",
      "monster", "magic", "hero", "treasure", "spell",
      "began", "went", "saw", "took", "ran",
    ],
  },
  {
    id: "g4-m7",
    grade: 4,
    number: 7,
    title: "Days to Remember",
    topics: ["Особенные дни", "Праздники", "Биография"],
    grammar: ["Past Simple (вопросы)", "Wh-questions"],
    vocabulary: [
      "birthday", "wedding", "concert", "festival", "carnival",
      "holiday", "ceremony", "anniversary", "graduation", "reunion",
      "memory", "diary", "album", "photo", "souvenir",
      "celebrate", "remember", "forget", "wish", "dream",
    ],
  },
  {
    id: "g4-m8",
    grade: 4,
    number: 8,
    title: "Places to Go",
    topics: ["Путешествия", "Страны", "Каникулы"],
    grammar: ["Going to (планы)", "Сравнительная степень прилагательных"],
    vocabulary: [
      "beach", "mountain", "lake", "river", "forest",
      "desert", "island", "valley", "hill", "ocean",
      "ticket", "passport", "luggage", "hotel", "tent",
      "swim", "sunbathe", "explore", "camp", "hike",
    ],
  },

  // Grade 5 · Modules 5–8
  {
    id: "g5-m5",
    grade: 5,
    number: 5,
    title: "World Animals",
    topics: ["Дикие животные", "Среда обитания", "Описание"],
    grammar: ["Present Simple (повторение)", "Adverbs of frequency"],
    vocabulary: [
      "habitat", "endangered", "predator", "prey", "wildlife",
      "savannah", "jungle", "ocean", "polar", "tropical",
      "mammal", "reptile", "insect", "amphibian", "bird",
      "wing", "tail", "claw", "fur", "feather",
    ],
  },
  {
    id: "g5-m6",
    grade: 5,
    number: 6,
    title: "Round the Clock",
    topics: ["Распорядок дня", "Время и часы", "Хобби"],
    grammar: ["Present Continuous", "Сравнение Present Simple / Continuous"],
    vocabulary: [
      "schedule", "appointment", "deadline", "alarm", "minute",
      "hour", "second", "quarter past", "half past", "quarter to",
      "wake up", "get dressed", "have breakfast", "leave home", "go to bed",
      "currently", "right now", "at the moment", "today", "this week",
    ],
  },
  {
    id: "g5-m7",
    grade: 5,
    number: 7,
    title: "In All Weathers",
    topics: ["Погода", "Климат", "Времена года"],
    grammar: ["Будущее время (will)", "Adjectives describing weather"],
    vocabulary: [
      "thunderstorm", "lightning", "blizzard", "hurricane", "drought",
      "humid", "freezing", "boiling", "mild", "stormy",
      "forecast", "temperature", "degree", "climate", "atmosphere",
      "rainbow", "fog", "frost", "hail", "breeze",
    ],
  },
  {
    id: "g5-m8",
    grade: 5,
    number: 8,
    title: "Special Days",
    topics: ["Праздники", "Традиции", "Семейные торжества"],
    grammar: ["Countable / uncountable nouns", "Some / any / much / many"],
    vocabulary: [
      "celebrate", "tradition", "custom", "ceremony", "feast",
      "decorate", "invite", "gift", "ribbon", "candle",
      "fireworks", "parade", "costume", "mask", "drum",
      "Christmas", "Easter", "Halloween", "Thanksgiving", "New Year",
    ],
  },

  // Grade 6 · Modules 5–8
  {
    id: "g6-m5",
    grade: 6,
    number: 5,
    title: "Feasts",
    topics: ["Праздники мира", "Национальная кухня", "Традиции"],
    grammar: ["Present Perfect (introduction)", "Have you ever …?"],
    vocabulary: [
      "feast", "banquet", "gathering", "ritual", "ceremony",
      "lantern", "fireworks", "barbecue", "picnic", "buffet",
      "dumpling", "pancake", "pumpkin", "turkey", "spice",
      "guest", "host", "toast", "speech", "menu",
    ],
  },
  {
    id: "g6-m6",
    grade: 6,
    number: 6,
    title: "Leisure Activities",
    topics: ["Досуг", "Спорт", "Развлечения"],
    grammar: ["Present Continuous (будущее значение)", "Like + ing"],
    vocabulary: [
      "skateboarding", "surfing", "rock climbing", "diving", "cycling",
      "hiking", "camping", "fishing", "gardening", "knitting",
      "painting", "photography", "chess", "cards", "puzzle",
      "free time", "spare time", "leisure", "weekend", "vacation",
    ],
  },
  {
    id: "g6-m7",
    grade: 6,
    number: 7,
    title: "Now and Then",
    topics: ["Прошлое и настоящее", "Технологии", "Биография"],
    grammar: ["Past Simple", "Used to"],
    vocabulary: [
      "ancient", "modern", "century", "decade", "era",
      "historic", "vintage", "antique", "futuristic", "outdated",
      "invention", "discovery", "tradition", "progress", "change",
      "great-grandparent", "ancestor", "descendant", "generation", "heritage",
    ],
  },
  {
    id: "g6-m8",
    grade: 6,
    number: 8,
    title: "Rules & Regulations",
    topics: ["Правила", "Школьная жизнь", "Безопасность"],
    grammar: ["Modal verbs (must, mustn't, have to)", "Imperatives"],
    vocabulary: [
      "rule", "law", "regulation", "permission", "warning",
      "punishment", "fine", "detention", "report", "behaviour",
      "must", "have to", "should", "ought to", "be allowed to",
      "uniform", "respect", "discipline", "obey", "break the rule",
    ],
  },

  // Grade 7 · Modules 5–8
  {
    id: "g7-m5",
    grade: 7,
    number: 5,
    title: "What the Future Holds",
    topics: ["Будущее", "Технологии", "Прогнозы"],
    grammar: ["Future Simple (will)", "Be going to"],
    vocabulary: [
      "robot", "spaceship", "colony", "explore", "predict",
      "artificial intelligence", "virtual reality", "drone", "smart device", "automation",
      "renewable", "sustainable", "eco-friendly", "innovation", "breakthrough",
      "scientist", "engineer", "discovery", "experiment", "laboratory",
    ],
  },
  {
    id: "g7-m6",
    grade: 7,
    number: 6,
    title: "Having Fun",
    topics: ["Развлечения", "Парки аттракционов", "Игры"],
    grammar: ["Present Perfect Continuous", "For / since"],
    vocabulary: [
      "amusement park", "roller coaster", "ticket", "queue", "crowd",
      "attraction", "ride", "performance", "show", "concert",
      "comedy", "drama", "stage", "audience", "applause",
      "theme park", "fair", "circus", "carnival", "festival",
    ],
  },
  {
    id: "g7-m7",
    grade: 7,
    number: 7,
    title: "In the Spotlight",
    topics: ["Знаменитости", "Кино", "Музыка"],
    grammar: ["Степени сравнения прилагательных", "Superlative"],
    vocabulary: [
      "celebrity", "actor", "actress", "director", "producer",
      "fan", "interview", "fame", "talent", "rehearsal",
      "soundtrack", "lyrics", "melody", "rhythm", "performance",
      "blockbuster", "premiere", "review", "rating", "award",
    ],
  },
  {
    id: "g7-m8",
    grade: 7,
    number: 8,
    title: "Green Issues",
    topics: ["Экология", "Окружающая среда", "Защита природы"],
    grammar: ["Conditional sentences (Type 1)", "If / unless"],
    vocabulary: [
      "pollution", "recycling", "global warming", "climate change", "deforestation",
      "endangered", "extinction", "habitat", "ecosystem", "biodiversity",
      "renewable", "sustainable", "organic", "compost", "litter",
      "save", "protect", "reduce", "reuse", "preserve",
    ],
  },

  // Grade 8 · Modules 5–8
  {
    id: "g8-m5",
    grade: 8,
    number: 5,
    title: "Global Issues",
    topics: ["Экология", "Природные катастрофы", "Помощь"],
    grammar: ["Passive voice", "Conditional Type 2"],
    vocabulary: [
      "earthquake", "volcano", "tsunami", "tornado", "flood",
      "drought", "wildfire", "avalanche", "landslide", "cyclone",
      "rescue", "shelter", "aid", "donation", "volunteer",
      "charity", "crisis", "emergency", "evacuation", "victim",
    ],
  },
  {
    id: "g8-m6",
    grade: 8,
    number: 6,
    title: "Culture Exchanges",
    topics: ["Путешествия", "Культура", "Языки"],
    grammar: ["Reported speech", "Indirect questions"],
    vocabulary: [
      "tourist", "guide", "souvenir", "landmark", "monument",
      "destination", "itinerary", "sightseeing", "tour", "excursion",
      "tradition", "custom", "etiquette", "gesture", "taboo",
      "bilingual", "translate", "interpret", "fluent", "accent",
    ],
  },
  {
    id: "g8-m7",
    grade: 8,
    number: 7,
    title: "Education",
    topics: ["Образование", "Экзамены", "Карьера"],
    grammar: ["Modal verbs of obligation", "Should / ought to"],
    vocabulary: [
      "university", "college", "degree", "diploma", "scholarship",
      "lecture", "seminar", "tutorial", "thesis", "research",
      "exam", "test", "quiz", "essay", "project",
      "graduate", "undergraduate", "professor", "academic", "campus",
    ],
  },
  {
    id: "g8-m8",
    grade: 8,
    number: 8,
    title: "Pastimes",
    topics: ["Хобби", "Спорт", "Здоровый образ жизни"],
    grammar: ["Present Perfect vs Past Simple", "Just / already / yet"],
    vocabulary: [
      "fitness", "workout", "stamina", "strength", "flexibility",
      "yoga", "pilates", "aerobics", "marathon", "triathlon",
      "diet", "nutrition", "calorie", "vitamin", "protein",
      "hobby", "pastime", "passion", "enthusiast", "addicted",
    ],
  },

  // Grade 5 · Modules 9–10 (full Spotlight syllabus)
  {
    id: "g5-m9",
    grade: 5,
    number: 9,
    title: "Modern Living",
    topics: ["Магазины", "Покупки", "Свободное время"],
    grammar: ["Present Perfect", "Have / has been to"],
    vocabulary: [
      "shopping centre", "supermarket", "department store", "bakery", "butcher's",
      "florist", "newsagent", "chemist", "boutique", "kiosk",
      "receipt", "bargain", "discount", "voucher", "refund",
      "trolley", "basket", "checkout", "cashier", "delivery",
    ],
  },
  {
    id: "g5-m10",
    grade: 5,
    number: 10,
    title: "Holidays",
    topics: ["Каникулы", "Путешествия", "Виды отдыха"],
    grammar: ["Be going to", "Будущее планирование"],
    vocabulary: [
      "destination", "resort", "beach", "mountains", "countryside",
      "package tour", "cruise", "safari", "adventure", "sightseeing",
      "suitcase", "backpack", "passport", "visa", "boarding pass",
      "souvenir", "postcard", "memory", "experience", "journey",
    ],
  },

  // Grade 6 · Modules 9–10
  {
    id: "g6-m9",
    grade: 6,
    number: 9,
    title: "Food & Refreshments",
    topics: ["Еда", "Напитки", "Кафе и рестораны"],
    grammar: ["Countable / uncountable nouns", "A few / a little / a lot of"],
    vocabulary: [
      "menu", "starter", "main course", "dessert", "side dish",
      "appetizer", "soup", "salad", "sandwich", "snack",
      "spicy", "salty", "sweet", "sour", "bitter",
      "waiter", "waitress", "chef", "tip", "bill",
    ],
  },
  {
    id: "g6-m10",
    grade: 6,
    number: 10,
    title: "Holiday Time",
    topics: ["Отпуск", "Бронирование", "Активный отдых"],
    grammar: ["Future plans (will / be going to)", "Time clauses"],
    vocabulary: [
      "booking", "reservation", "check-in", "check-out", "receptionist",
      "single room", "double room", "suite", "balcony", "view",
      "all-inclusive", "half-board", "self-catering", "currency", "exchange rate",
      "guidebook", "map", "compass", "binoculars", "camera",
    ],
  },

  // Grade 7 · Modules 9–10
  {
    id: "g7-m9",
    grade: 7,
    number: 9,
    title: "Shopping Time",
    topics: ["Шопинг", "Деньги", "Реклама"],
    grammar: ["Present Perfect vs Past Simple", "Already / yet / just"],
    vocabulary: [
      "advertisement", "commercial", "brand", "logo", "slogan",
      "consumer", "customer", "client", "supplier", "retailer",
      "afford", "save", "spend", "borrow", "lend",
      "expensive", "cheap", "affordable", "valuable", "priceless",
    ],
  },
  {
    id: "g7-m10",
    grade: 7,
    number: 10,
    title: "Healthy Body, Healthy Mind",
    topics: ["Здоровье", "Стресс", "Образ жизни"],
    grammar: ["Reflexive pronouns", "Reported speech (introduction)"],
    vocabulary: [
      "headache", "toothache", "stomachache", "backache", "earache",
      "cough", "sneeze", "fever", "rash", "injury",
      "stress", "anxiety", "relaxation", "meditation", "balance",
      "recover", "heal", "treat", "prescribe", "diagnose",
    ],
  },
];

export function modulesByGrade(grade: Grade): CurriculumModule[] {
  return CURRICULUM.filter((m) => m.grade === grade).sort((a, b) => a.number - b.number);
}

export function moduleById(id: string): CurriculumModule | undefined {
  return CURRICULUM.find((m) => m.id === id);
}

export function moduleByGradeNumber(grade: Grade, number: number): CurriculumModule | undefined {
  return CURRICULUM.find((m) => m.grade === grade && m.number === number);
}

export const GRADES: Grade[] = [2, 3, 4, 5, 6, 7, 8];
