import type { VocabWord, Grade } from "@/types";
import { CURRICULUM } from "@/lib/curriculum";

/**
 * Comprehensive Spotlight 2-8 vocabulary bank.
 * ~560 words across 28 modules — average 20 words/module — broadly aligned
 * with Express Publishing/«Просвещение» Spotlight syllabus, expanded with
 * neighbour-thematic items so flash-cards have useful recombinations.
 *
 * Each entry: translation (RU), part of speech (RU short form), short example
 * sentence, optional IPA-like transcription. Adding a new word = adding here
 * AND adding the lemma to the corresponding module in `curriculum.ts`.
 */

const TRANSLATIONS: Record<
  string,
  { translation: string; pos: string; example: string; tr?: string }
> = {
  // === Grade 2 / Module 1: My Home ===
  bedroom: { translation: "спальня", pos: "сущ.", example: "My bedroom is small." },
  kitchen: { translation: "кухня", pos: "сущ.", example: "Mum is in the kitchen." },
  bathroom: { translation: "ванная", pos: "сущ.", example: "The bathroom is upstairs." },
  garden: { translation: "сад", pos: "сущ.", example: "We play in the garden." },
  "dining room": { translation: "столовая", pos: "сущ.", example: "We have dinner in the dining room." },
  "living room": { translation: "гостиная", pos: "сущ.", example: "The TV is in the living room." },
  hall: { translation: "прихожая", pos: "сущ.", example: "Coats are in the hall." },
  stairs: { translation: "лестница", pos: "сущ.", example: "Run up the stairs." },
  door: { translation: "дверь", pos: "сущ.", example: "Close the door, please." },
  window: { translation: "окно", pos: "сущ.", example: "Open the window!" },
  roof: { translation: "крыша", pos: "сущ.", example: "A cat is on the roof." },
  chair: { translation: "стул", pos: "сущ.", example: "Sit on the chair." },
  table: { translation: "стол", pos: "сущ.", example: "The book is on the table." },
  bed: { translation: "кровать", pos: "сущ.", example: "Make your bed." },
  sofa: { translation: "диван", pos: "сущ.", example: "Dad is on the sofa." },
  lamp: { translation: "лампа", pos: "сущ.", example: "Turn on the lamp." },
  TV: { translation: "телевизор", pos: "сущ.", example: "We watch TV in the evening." },
  clock: { translation: "часы", pos: "сущ.", example: "The clock is on the wall." },
  picture: { translation: "картина", pos: "сущ.", example: "A nice picture of the sea." },
  carpet: { translation: "ковёр", pos: "сущ.", example: "The carpet is red." },

  // === Grade 2 / Module 2: My Birthday ===
  cake: { translation: "торт", pos: "сущ.", example: "I like chocolate cake." },
  candles: { translation: "свечи", pos: "сущ.", example: "Ten candles on the cake." },
  "ice cream": { translation: "мороженое", pos: "сущ.", example: "I want strawberry ice cream." },
  chocolate: { translation: "шоколад", pos: "сущ.", example: "Dark chocolate is bitter." },
  lemonade: { translation: "лимонад", pos: "сущ.", example: "A glass of lemonade, please." },
  balloon: { translation: "воздушный шарик", pos: "сущ.", example: "A red balloon." },
  present: { translation: "подарок", pos: "сущ.", example: "Open your present!" },
  party: { translation: "вечеринка", pos: "сущ.", example: "A birthday party." },
  friend: { translation: "друг", pos: "сущ.", example: "My best friend." },
  song: { translation: "песня", pos: "сущ.", example: "Sing a happy song." },
  dance: { translation: "танец / танцевать", pos: "гл./сущ.", example: "Let's dance!" },
  happy: { translation: "счастливый", pos: "прил.", example: "I am happy today." },
  year: { translation: "год", pos: "сущ.", example: "I am ten years old." },
  old: { translation: "лет / старый", pos: "прил.", example: "How old are you?" },
  number: { translation: "число", pos: "сущ.", example: "What's your number?" },
  one: { translation: "один", pos: "числ.", example: "I have one cat." },
  two: { translation: "два", pos: "числ.", example: "Two boys are running." },
  three: { translation: "три", pos: "числ.", example: "Three apples on the table." },
  four: { translation: "четыре", pos: "числ.", example: "Four windows." },
  five: { translation: "пять", pos: "числ.", example: "Five candles on the cake." },

  // === Grade 2 / Module 3: My Animals ===
  fish: { translation: "рыба", pos: "сущ.", example: "I have got a fish." },
  bird: { translation: "птица", pos: "сущ.", example: "The bird can fly." },
  frog: { translation: "лягушка", pos: "сущ.", example: "A frog can jump." },
  horse: { translation: "лошадь", pos: "сущ.", example: "Horses live on the farm." },
  chimp: { translation: "шимпанзе", pos: "сущ.", example: "The chimp is funny." },
  dog: { translation: "собака", pos: "сущ.", example: "My dog is friendly." },
  cat: { translation: "кот / кошка", pos: "сущ.", example: "The cat is sleeping." },
  rabbit: { translation: "кролик", pos: "сущ.", example: "A white rabbit." },
  mouse: { translation: "мышь", pos: "сущ.", example: "A small grey mouse." },
  hen: { translation: "курица", pos: "сущ.", example: "The hen has chicks." },
  cow: { translation: "корова", pos: "сущ.", example: "The cow gives milk." },
  sheep: { translation: "овца", pos: "сущ.", example: "Sheep eat grass." },
  pig: { translation: "свинья", pos: "сущ.", example: "Pigs are pink." },
  duck: { translation: "утка", pos: "сущ.", example: "Ducks swim in the pond." },
  swan: { translation: "лебедь", pos: "сущ.", example: "A white swan." },
  jump: { translation: "прыгать", pos: "гл.", example: "I can jump high." },
  swim: { translation: "плавать", pos: "гл.", example: "Fish can swim." },
  fly: { translation: "летать", pos: "гл.", example: "Birds can fly." },
  run: { translation: "бегать", pos: "гл.", example: "I can run fast." },
  climb: { translation: "лазать", pos: "гл.", example: "Cats can climb a tree." },

  // === Grade 2 / Module 4: My Toys ===
  "teddy bear": { translation: "плюшевый мишка", pos: "сущ.", example: "I have a teddy bear." },
  "toy soldier": { translation: "солдатик", pos: "сущ.", example: "A toy soldier is on the shelf." },
  ballerina: { translation: "балерина", pos: "сущ.", example: "The ballerina is dancing." },
  shelf: { translation: "полка", pos: "сущ.", example: "Put the book on the shelf." },
  "musical box": { translation: "музыкальная шкатулка", pos: "сущ.", example: "Open the musical box." },
  doll: { translation: "кукла", pos: "сущ.", example: "She has a new doll." },
  ball: { translation: "мяч", pos: "сущ.", example: "Kick the ball!" },
  kite: { translation: "воздушный змей", pos: "сущ.", example: "A blue kite in the sky." },
  drum: { translation: "барабан", pos: "сущ.", example: "Play the drum loudly." },
  puzzle: { translation: "пазл", pos: "сущ.", example: "I love puzzles." },
  robot: { translation: "робот", pos: "сущ.", example: "A small toy robot." },
  car: { translation: "машина", pos: "сущ.", example: "A red toy car." },
  bike: { translation: "велосипед", pos: "сущ.", example: "I ride my bike." },
  plane: { translation: "самолёт", pos: "сущ.", example: "The plane is flying high." },
  train: { translation: "поезд", pos: "сущ.", example: "The train is fast." },
  in: { translation: "в", pos: "предл.", example: "The toy is in the box." },
  on: { translation: "на", pos: "предл.", example: "The book is on the desk." },
  under: { translation: "под", pos: "предл.", example: "The ball is under the chair." },
  behind: { translation: "за", pos: "предл.", example: "The cat is behind the sofa." },
  near: { translation: "рядом", pos: "предл.", example: "The shop is near the school." },

  // === Grade 3 / Module 1: School Days ===
  Maths: { translation: "математика", pos: "сущ.", example: "Maths is my favourite subject." },
  English: { translation: "английский", pos: "сущ.", example: "We learn English." },
  PE: { translation: "физкультура", pos: "сущ.", example: "We have PE on Monday." },
  Science: { translation: "естествознание", pos: "сущ.", example: "We do experiments in Science." },
  Art: { translation: "рисование", pos: "сущ.", example: "I love Art class." },
  Music: { translation: "музыка", pos: "сущ.", example: "Music class is fun." },
  History: { translation: "история", pos: "сущ.", example: "History is interesting." },
  Geography: { translation: "география", pos: "сущ.", example: "Geography teaches about countries." },
  Russian: { translation: "русский язык", pos: "сущ.", example: "Russian is our native language." },
  IT: { translation: "информатика", pos: "сущ.", example: "I love IT class." },
  lesson: { translation: "урок", pos: "сущ.", example: "The lesson is over." },
  class: { translation: "класс / занятие", pos: "сущ.", example: "Our class is big." },
  pupil: { translation: "ученик", pos: "сущ.", example: "He is a good pupil." },
  teacher: { translation: "учитель", pos: "сущ.", example: "Our teacher is kind." },
  school: { translation: "школа", pos: "сущ.", example: "I go to school by bus." },
  book: { translation: "книга", pos: "сущ.", example: "Open your book." },
  pen: { translation: "ручка", pos: "сущ.", example: "Take a pen and write." },
  pencil: { translation: "карандаш", pos: "сущ.", example: "Sharpen your pencil." },
  ruler: { translation: "линейка", pos: "сущ.", example: "Use a ruler to draw." },
  rubber: { translation: "ластик", pos: "сущ.", example: "Pass me the rubber." },

  // === Grade 3 / Module 2: Family Moments ===
  grandma: { translation: "бабушка", pos: "сущ.", example: "My grandma bakes pies." },
  grandpa: { translation: "дедушка", pos: "сущ.", example: "Grandpa tells stories." },
  cousin: { translation: "двоюродный брат/сестра", pos: "сущ.", example: "My cousin is ten." },
  uncle: { translation: "дядя", pos: "сущ.", example: "Uncle Tom is a pilot." },
  aunt: { translation: "тётя", pos: "сущ.", example: "Aunt Mary is kind." },
  mum: { translation: "мама", pos: "сущ.", example: "Mum is at home." },
  dad: { translation: "папа", pos: "сущ.", example: "Dad cooks well." },
  sister: { translation: "сестра", pos: "сущ.", example: "My sister is funny." },
  brother: { translation: "брат", pos: "сущ.", example: "I have an older brother." },
  parent: { translation: "родитель", pos: "сущ.", example: "My parents are doctors." },
  baby: { translation: "малыш", pos: "сущ.", example: "The baby is sleeping." },
  family: { translation: "семья", pos: "сущ.", example: "I love my family." },
  photo: { translation: "фото", pos: "сущ.", example: "A family photo." },
  love: { translation: "любить / любовь", pos: "гл./сущ.", example: "I love you." },
  hug: { translation: "обнимать / объятие", pos: "гл./сущ.", example: "Give me a hug." },
  kiss: { translation: "целовать / поцелуй", pos: "гл./сущ.", example: "A kiss for mum." },
  son: { translation: "сын", pos: "сущ.", example: "Their son is five." },
  daughter: { translation: "дочь", pos: "сущ.", example: "His daughter is at school." },
  wife: { translation: "жена", pos: "сущ.", example: "John's wife is a nurse." },
  husband: { translation: "муж", pos: "сущ.", example: "Her husband is a chef." },

  // === Grade 3 / Module 3: All the Things I Like ===
  pasta: { translation: "паста", pos: "сущ.", example: "I like pasta with cheese." },
  rice: { translation: "рис", pos: "сущ.", example: "Rice with fish is tasty." },
  meat: { translation: "мясо", pos: "сущ.", example: "We eat meat for dinner." },
  vegetables: { translation: "овощи", pos: "сущ.", example: "Vegetables are healthy." },
  fruit: { translation: "фрукты", pos: "сущ.", example: "Fruit is sweet and fresh." },
  apple: { translation: "яблоко", pos: "сущ.", example: "An apple a day." },
  banana: { translation: "банан", pos: "сущ.", example: "Yellow banana." },
  orange: { translation: "апельсин", pos: "сущ.", example: "An orange is round." },
  tomato: { translation: "помидор", pos: "сущ.", example: "A red tomato." },
  potato: { translation: "картофель", pos: "сущ.", example: "Potato chips, please." },
  sandwich: { translation: "сэндвич", pos: "сущ.", example: "Cheese sandwich for lunch." },
  soup: { translation: "суп", pos: "сущ.", example: "Hot soup for dinner." },
  salad: { translation: "салат", pos: "сущ.", example: "A green salad." },
  pizza: { translation: "пицца", pos: "сущ.", example: "I order pizza." },
  milk: { translation: "молоко", pos: "сущ.", example: "A glass of milk." },
  juice: { translation: "сок", pos: "сущ.", example: "Apple juice, please." },
  water: { translation: "вода", pos: "сущ.", example: "Drink more water." },
  tea: { translation: "чай", pos: "сущ.", example: "I like tea with lemon." },
  coffee: { translation: "кофе", pos: "сущ.", example: "Black coffee, no sugar." },

  // === Grade 3 / Module 4: Come In and Play! ===
  "rocking horse": { translation: "лошадка-качалка", pos: "сущ.", example: "The rocking horse is old." },
  computer: { translation: "компьютер", pos: "сущ.", example: "I play on the computer." },
  phone: { translation: "телефон", pos: "сущ.", example: "Pass me the phone." },
  camera: { translation: "фотоаппарат", pos: "сущ.", example: "Smile for the camera." },
  magazine: { translation: "журнал", pos: "сущ.", example: "A teen magazine." },
  "board game": { translation: "настольная игра", pos: "сущ.", example: "Let's play a board game." },
  card: { translation: "карта", pos: "сущ.", example: "Pick a card." },
  dice: { translation: "кубик", pos: "сущ.", example: "Roll the dice." },
  chess: { translation: "шахматы", pos: "сущ.", example: "I play chess with dad." },
  lego: { translation: "лего", pos: "сущ.", example: "I build with lego." },
  toy: { translation: "игрушка", pos: "сущ.", example: "A new toy." },
  game: { translation: "игра", pos: "сущ.", example: "A fun game." },
  room: { translation: "комната", pos: "сущ.", example: "My room is small." },
  play: { translation: "играть", pos: "гл.", example: "I play with my dog." },
  fun: { translation: "веселье", pos: "сущ.", example: "We had fun." },

  // === Grade 4 / Module 1: Back Together ===
  tall: { translation: "высокий", pos: "прил.", example: "My dad is tall." },
  short: { translation: "низкий / короткий", pos: "прил.", example: "Her hair is short." },
  funny: { translation: "весёлый", pos: "прил.", example: "A funny cartoon." },
  kind: { translation: "добрый", pos: "прил.", example: "She is very kind." },
  shy: { translation: "застенчивый", pos: "прил.", example: "He is shy with strangers." },
  friendly: { translation: "дружелюбный", pos: "прил.", example: "A friendly smile." },
  sad: { translation: "грустный", pos: "прил.", example: "He looks sad today." },
  angry: { translation: "сердитый", pos: "прил.", example: "Don't be angry." },
  tired: { translation: "уставший", pos: "прил.", example: "I'm tired after sport." },
  hair: { translation: "волосы", pos: "сущ.", example: "Long blond hair." },
  eyes: { translation: "глаза", pos: "сущ.", example: "Blue eyes." },
  nose: { translation: "нос", pos: "сущ.", example: "A small nose." },
  mouth: { translation: "рот", pos: "сущ.", example: "Open your mouth." },
  face: { translation: "лицо", pos: "сущ.", example: "Wash your face." },
  smile: { translation: "улыбка / улыбаться", pos: "гл./сущ.", example: "She has a nice smile." },
  laugh: { translation: "смеяться", pos: "гл.", example: "Don't laugh at him." },
  talk: { translation: "разговаривать", pos: "гл.", example: "Talk to me." },
  listen: { translation: "слушать", pos: "гл.", example: "Listen to the music." },

  // === Grade 4 / Module 2: Working Day ===
  doctor: { translation: "врач", pos: "сущ.", example: "The doctor helps us." },
  dentist: { translation: "стоматолог", pos: "сущ.", example: "The dentist fixes teeth." },
  farmer: { translation: "фермер", pos: "сущ.", example: "The farmer works on a farm." },
  waiter: { translation: "официант", pos: "сущ.", example: "The waiter is polite." },
  mechanic: { translation: "механик", pos: "сущ.", example: "The mechanic repairs cars." },
  nurse: { translation: "медсестра", pos: "сущ.", example: "The nurse is kind." },
  pilot: { translation: "пилот", pos: "сущ.", example: "The pilot flies planes." },
  postman: { translation: "почтальон", pos: "сущ.", example: "The postman brings letters." },
  baker: { translation: "пекарь", pos: "сущ.", example: "The baker makes bread." },
  vet: { translation: "ветеринар", pos: "сущ.", example: "The vet helps animals." },
  fireman: { translation: "пожарный", pos: "сущ.", example: "Firemen are brave." },
  policeman: { translation: "полицейский", pos: "сущ.", example: "The policeman helps." },
  driver: { translation: "водитель", pos: "сущ.", example: "Bus driver." },
  cleaner: { translation: "уборщик", pos: "сущ.", example: "Cleaner at the office." },
  work: { translation: "работа / работать", pos: "гл./сущ.", example: "I go to work at 8." },
  job: { translation: "работа", pos: "сущ.", example: "She has a new job." },
  hospital: { translation: "больница", pos: "сущ.", example: "He is in the hospital." },
  restaurant: { translation: "ресторан", pos: "сущ.", example: "A nice restaurant." },
  factory: { translation: "фабрика", pos: "сущ.", example: "He works at a factory." },

  // === Grade 4 / Module 3: Tasty Treats ===
  bread: { translation: "хлеб", pos: "сущ.", example: "Bread and butter." },
  butter: { translation: "масло", pos: "сущ.", example: "Spread butter on the bread." },
  cheese: { translation: "сыр", pos: "сущ.", example: "Do you like cheese?" },
  honey: { translation: "мёд", pos: "сущ.", example: "Honey is sweet." },
  cereal: { translation: "хлопья", pos: "сущ.", example: "Cereal for breakfast." },
  jam: { translation: "варенье", pos: "сущ.", example: "Strawberry jam." },
  biscuit: { translation: "печенье", pos: "сущ.", example: "Tea and biscuits." },
  sweet: { translation: "сладкое / сладкий", pos: "прил./сущ.", example: "A sweet apple." },
  sugar: { translation: "сахар", pos: "сущ.", example: "Two spoons of sugar." },
  salt: { translation: "соль", pos: "сущ.", example: "Pass the salt." },
  pepper: { translation: "перец", pos: "сущ.", example: "Salt and pepper." },
  oil: { translation: "масло (растительное)", pos: "сущ.", example: "Olive oil." },
  flour: { translation: "мука", pos: "сущ.", example: "We need flour for cake." },
  egg: { translation: "яйцо", pos: "сущ.", example: "I eat one egg." },
  lemon: { translation: "лимон", pos: "сущ.", example: "A slice of lemon." },
  strawberry: { translation: "клубника", pos: "сущ.", example: "Sweet strawberry." },
  grape: { translation: "виноград", pos: "сущ.", example: "Green grapes." },
  melon: { translation: "дыня", pos: "сущ.", example: "Sweet melon in summer." },

  // === Grade 4 / Module 4: At the Zoo ===
  lion: { translation: "лев", pos: "сущ.", example: "The lion is strong." },
  elephant: { translation: "слон", pos: "сущ.", example: "An elephant is big." },
  giraffe: { translation: "жираф", pos: "сущ.", example: "The giraffe is tall." },
  peacock: { translation: "павлин", pos: "сущ.", example: "A peacock has a beautiful tail." },
  seal: { translation: "тюлень", pos: "сущ.", example: "The seal is swimming." },
  tiger: { translation: "тигр", pos: "сущ.", example: "Orange tiger." },
  monkey: { translation: "обезьяна", pos: "сущ.", example: "Monkeys eat bananas." },
  bear: { translation: "медведь", pos: "сущ.", example: "A brown bear." },
  kangaroo: { translation: "кенгуру", pos: "сущ.", example: "Kangaroos jump." },
  zebra: { translation: "зебра", pos: "сущ.", example: "Zebras have stripes." },
  panda: { translation: "панда", pos: "сущ.", example: "Pandas eat bamboo." },
  crocodile: { translation: "крокодил", pos: "сущ.", example: "Beware of the crocodile." },
  snake: { translation: "змея", pos: "сущ.", example: "A long green snake." },
  parrot: { translation: "попугай", pos: "сущ.", example: "A talking parrot." },
  eagle: { translation: "орёл", pos: "сущ.", example: "An eagle flies high." },
  wing: { translation: "крыло", pos: "сущ.", example: "Birds have two wings." },
  paw: { translation: "лапа", pos: "сущ.", example: "Cat's paws." },
  tail: { translation: "хвост", pos: "сущ.", example: "A long tail." },
  fur: { translation: "мех", pos: "сущ.", example: "Soft fur." },
  feather: { translation: "перо", pos: "сущ.", example: "A bird's feather." },

  // === Grade 5 / Module 1: School Days ===
  timetable: { translation: "расписание", pos: "сущ.", example: "Look at the timetable." },
  schoolbag: { translation: "портфель", pos: "сущ.", example: "My schoolbag is heavy." },
  headmaster: { translation: "директор школы", pos: "сущ.", example: "The headmaster is in his office." },
  subject: { translation: "предмет", pos: "сущ.", example: "History is my favourite subject." },
  term: { translation: "четверть", pos: "сущ.", example: "The first term ends in October." },
  break: { translation: "перемена", pos: "сущ.", example: "We chat at break." },
  library: { translation: "библиотека", pos: "сущ.", example: "Borrow a book at the library." },
  gym: { translation: "спортзал", pos: "сущ.", example: "PE in the gym." },
  canteen: { translation: "столовая (школьная)", pos: "сущ.", example: "Lunch in the canteen." },
  uniform: { translation: "форма", pos: "сущ.", example: "School uniform is blue." },
  homework: { translation: "домашнее задание", pos: "сущ.", example: "Do your homework." },
  exam: { translation: "экзамен", pos: "сущ.", example: "An English exam tomorrow." },
  mark: { translation: "оценка", pos: "сущ.", example: "She got a high mark." },
  classroom: { translation: "кабинет", pos: "сущ.", example: "Our classroom is bright." },
  blackboard: { translation: "доска", pos: "сущ.", example: "Write on the blackboard." },
  chalk: { translation: "мел", pos: "сущ.", example: "White chalk." },
  desk: { translation: "парта", pos: "сущ.", example: "Sit at the desk." },
  locker: { translation: "шкафчик", pos: "сущ.", example: "My books are in the locker." },

  // === Grade 5 / Module 2: That's Me! ===
  Russia: { translation: "Россия", pos: "сущ.", example: "I live in Russia." },
  Britain: { translation: "Британия", pos: "сущ.", example: "London is in Britain." },
  Spain: { translation: "Испания", pos: "сущ.", example: "Spain is sunny." },
  passport: { translation: "паспорт", pos: "сущ.", example: "I need my passport." },
  nationality: { translation: "национальность", pos: "сущ.", example: "What nationality are you?" },
  France: { translation: "Франция", pos: "сущ.", example: "Paris is in France." },
  Germany: { translation: "Германия", pos: "сущ.", example: "Berlin is in Germany." },
  Italy: { translation: "Италия", pos: "сущ.", example: "I'd like to visit Italy." },
  USA: { translation: "США", pos: "сущ.", example: "New York is in the USA." },
  Canada: { translation: "Канада", pos: "сущ.", example: "Canada is huge." },
  British: { translation: "британский", pos: "прил.", example: "A British accent." },
  French: { translation: "французский", pos: "прил.", example: "French food is famous." },
  German: { translation: "немецкий", pos: "прил.", example: "German cars." },
  Italian: { translation: "итальянский", pos: "прил.", example: "Italian pizza." },
  language: { translation: "язык", pos: "сущ.", example: "I speak two languages." },
  country: { translation: "страна", pos: "сущ.", example: "Russia is a big country." },
  capital: { translation: "столица", pos: "сущ.", example: "Moscow is the capital." },
  flag: { translation: "флаг", pos: "сущ.", example: "The flag is red." },
  citizen: { translation: "гражданин", pos: "сущ.", example: "A Russian citizen." },

  // === Grade 5 / Module 3: My Home, My Castle ===
  armchair: { translation: "кресло", pos: "сущ.", example: "Sit in the armchair." },
  fridge: { translation: "холодильник", pos: "сущ.", example: "Milk is in the fridge." },
  mirror: { translation: "зеркало", pos: "сущ.", example: "Look at the mirror." },
  wardrobe: { translation: "шкаф", pos: "сущ.", example: "Put your coat in the wardrobe." },
  cushion: { translation: "подушка декоративная", pos: "сущ.", example: "A soft cushion." },
  bookcase: { translation: "книжный шкаф", pos: "сущ.", example: "A wooden bookcase." },
  curtains: { translation: "шторы", pos: "сущ.", example: "Close the curtains." },
  painting: { translation: "картина", pos: "сущ.", example: "An old painting." },
  vase: { translation: "ваза", pos: "сущ.", example: "Flowers in a vase." },
  bath: { translation: "ванна", pos: "сущ.", example: "Take a hot bath." },
  shower: { translation: "душ", pos: "сущ.", example: "I take a shower in the morning." },
  sink: { translation: "раковина", pos: "сущ.", example: "Wash hands in the sink." },
  oven: { translation: "духовка", pos: "сущ.", example: "Bake the cake in the oven." },
  cooker: { translation: "плита", pos: "сущ.", example: "An electric cooker." },
  dishwasher: { translation: "посудомойка", pos: "сущ.", example: "Load the dishwasher." },
  "washing machine": { translation: "стиральная машина", pos: "сущ.", example: "Use the washing machine." },

  // === Grade 5 / Module 4: Family Ties ===
  brave: { translation: "смелый", pos: "прил.", example: "A brave soldier." },
  clever: { translation: "умный", pos: "прил.", example: "She is a clever girl." },
  noisy: { translation: "шумный", pos: "прил.", example: "A noisy street." },
  patient: { translation: "терпеливый", pos: "прил.", example: "Teachers must be patient." },
  lazy: { translation: "ленивый", pos: "прил.", example: "Don't be lazy." },
  helpful: { translation: "услужливый", pos: "прил.", example: "He is very helpful." },
  honest: { translation: "честный", pos: "прил.", example: "An honest answer." },
  twin: { translation: "близнец", pos: "сущ.", example: "Identical twins." },
  "only child": { translation: "единственный ребёнок", pos: "сущ.", example: "She's an only child." },
  niece: { translation: "племянница", pos: "сущ.", example: "My niece is six." },
  nephew: { translation: "племянник", pos: "сущ.", example: "My nephew loves football." },
  stepfather: { translation: "отчим", pos: "сущ.", example: "Her stepfather is kind." },
  stepmother: { translation: "мачеха", pos: "сущ.", example: "His stepmother is friendly." },
  grandparent: { translation: "бабушка/дедушка", pos: "сущ.", example: "Grandparents spoil grandchildren." },
  relative: { translation: "родственник", pos: "сущ.", example: "Distant relatives." },
  "family tree": { translation: "генеалогическое древо", pos: "сущ.", example: "Draw a family tree." },

  // === Grade 6 / Module 1: Who's Who? ===
  "ID card": { translation: "удостоверение", pos: "сущ.", example: "Show me your ID card." },
  nickname: { translation: "прозвище", pos: "сущ.", example: "My nickname is Tiger." },
  address: { translation: "адрес", pos: "сущ.", example: "Write your address." },
  postcode: { translation: "индекс", pos: "сущ.", example: "The postcode is 101000." },
  signature: { translation: "подпись", pos: "сущ.", example: "Put your signature here." },
  age: { translation: "возраст", pos: "сущ.", example: "What is your age?" },
  birthday: { translation: "день рождения", pos: "сущ.", example: "Happy birthday!" },
  hobby: { translation: "хобби", pos: "сущ.", example: "Music is my hobby." },
  contact: { translation: "контакт", pos: "сущ.", example: "My contact details." },
  email: { translation: "электронная почта", pos: "сущ.", example: "Send me an email." },
  "phone number": { translation: "номер телефона", pos: "сущ.", example: "What's your phone number?" },
  "full name": { translation: "полное имя", pos: "сущ.", example: "Write your full name." },
  surname: { translation: "фамилия", pos: "сущ.", example: "My surname is Smith." },
  "first name": { translation: "имя", pos: "сущ.", example: "First name: Anna." },
  "middle name": { translation: "отчество", pos: "сущ.", example: "His middle name is John." },
  city: { translation: "город", pos: "сущ.", example: "Moscow is a big city." },
  street: { translation: "улица", pos: "сущ.", example: "Baker Street." },
  house: { translation: "дом", pos: "сущ.", example: "A small house." },
  flat: { translation: "квартира", pos: "сущ.", example: "We live in a flat." },

  // === Grade 6 / Module 2: Here We Are ===
  calendar: { translation: "календарь", pos: "сущ.", example: "Mark the day on the calendar." },
  celebration: { translation: "праздник", pos: "сущ.", example: "A big celebration." },
  month: { translation: "месяц", pos: "сущ.", example: "July is a hot month." },
  season: { translation: "время года", pos: "сущ.", example: "Winter is a cold season." },
  festival: { translation: "фестиваль", pos: "сущ.", example: "The festival is in summer." },
  weekday: { translation: "будний день", pos: "сущ.", example: "Monday is a weekday." },
  holiday: { translation: "праздник / каникулы", pos: "сущ.", example: "Summer holidays start in June." },
  anniversary: { translation: "годовщина", pos: "сущ.", example: "Wedding anniversary." },
  ceremony: { translation: "церемония", pos: "сущ.", example: "An opening ceremony." },
  January: { translation: "январь", pos: "сущ.", example: "Cold January." },
  February: { translation: "февраль", pos: "сущ.", example: "Snowy February." },
  March: { translation: "март", pos: "сущ.", example: "March is windy." },
  July: { translation: "июль", pos: "сущ.", example: "Hot July." },
  autumn: { translation: "осень", pos: "сущ.", example: "Autumn leaves." },
  summer: { translation: "лето", pos: "сущ.", example: "I love summer." },
  winter: { translation: "зима", pos: "сущ.", example: "Cold winter." },
  spring: { translation: "весна", pos: "сущ.", example: "Spring flowers." },
  century: { translation: "век", pos: "сущ.", example: "The 21st century." },
  decade: { translation: "десятилетие", pos: "сущ.", example: "Two decades ago." },

  // === Grade 6 / Module 3: Getting Around ===
  bicycle: { translation: "велосипед", pos: "сущ.", example: "I ride my bicycle to school." },
  underground: { translation: "метро", pos: "сущ.", example: "Take the underground." },
  helicopter: { translation: "вертолёт", pos: "сущ.", example: "A helicopter is flying." },
  tram: { translation: "трамвай", pos: "сущ.", example: "The tram is yellow." },
  motorbike: { translation: "мотоцикл", pos: "сущ.", example: "Dad has a motorbike." },
  bus: { translation: "автобус", pos: "сущ.", example: "Take bus number 5." },
  ferry: { translation: "паром", pos: "сущ.", example: "A ferry across the river." },
  taxi: { translation: "такси", pos: "сущ.", example: "Call a taxi." },
  ship: { translation: "корабль", pos: "сущ.", example: "A big ship." },
  boat: { translation: "лодка", pos: "сущ.", example: "A small boat." },
  lorry: { translation: "грузовик", pos: "сущ.", example: "A red lorry." },
  van: { translation: "фургон", pos: "сущ.", example: "Delivery van." },
  station: { translation: "станция", pos: "сущ.", example: "Train station." },
  airport: { translation: "аэропорт", pos: "сущ.", example: "We arrived at the airport." },
  port: { translation: "порт", pos: "сущ.", example: "The ship is at the port." },
  road: { translation: "дорога", pos: "сущ.", example: "Cross the road carefully." },
  "traffic light": { translation: "светофор", pos: "сущ.", example: "Wait for the traffic light." },

  // === Grade 6 / Module 4: Day After Day ===
  routine: { translation: "распорядок", pos: "сущ.", example: "My daily routine." },
  "spare time": { translation: "свободное время", pos: "сущ.", example: "In my spare time I read." },
  weekend: { translation: "выходные", pos: "сущ.", example: "On the weekend I sleep in." },
  habit: { translation: "привычка", pos: "сущ.", example: "Reading is a good habit." },
  "alarm clock": { translation: "будильник", pos: "сущ.", example: "Set the alarm clock." },
  breakfast: { translation: "завтрак", pos: "сущ.", example: "Toast for breakfast." },
  lunch: { translation: "обед", pos: "сущ.", example: "Lunch at noon." },
  dinner: { translation: "ужин", pos: "сущ.", example: "Family dinner." },
  brush: { translation: "чистить (зубы) / щётка", pos: "гл./сущ.", example: "Brush your teeth." },
  dress: { translation: "одеваться / платье", pos: "гл./сущ.", example: "Dress warmly." },
  sleep: { translation: "спать", pos: "гл.", example: "I sleep eight hours." },
  "wake up": { translation: "просыпаться", pos: "гл.", example: "I wake up at 7." },
  "get up": { translation: "вставать", pos: "гл.", example: "I get up early." },
  "go to bed": { translation: "ложиться спать", pos: "гл.", example: "Go to bed at ten." },
  daily: { translation: "ежедневный", pos: "прил.", example: "Daily news." },
  often: { translation: "часто", pos: "нар.", example: "I often read." },
  sometimes: { translation: "иногда", pos: "нар.", example: "Sometimes we go out." },

  // === Grade 7 / Module 1: Lifestyles ===
  countryside: { translation: "сельская местность", pos: "сущ.", example: "We go to the countryside in summer." },
  suburbs: { translation: "пригород", pos: "сущ.", example: "They live in the suburbs." },
  skyscraper: { translation: "небоскрёб", pos: "сущ.", example: "The skyscraper is 50 floors high." },
  cottage: { translation: "коттедж", pos: "сущ.", example: "A lovely little cottage." },
  neighborhood: { translation: "район", pos: "сущ.", example: "A safe neighborhood." },
  downtown: { translation: "центр города", pos: "сущ.", example: "Downtown traffic is heavy." },
  village: { translation: "деревня", pos: "сущ.", example: "A small village." },
  town: { translation: "город / городок", pos: "сущ.", example: "A historic town." },
  urban: { translation: "городской", pos: "прил.", example: "Urban lifestyle." },
  rural: { translation: "сельский", pos: "прил.", example: "Rural areas are quiet." },
  busy: { translation: "оживлённый", pos: "прил.", example: "A busy street." },
  quiet: { translation: "тихий", pos: "прил.", example: "A quiet evening." },
  peaceful: { translation: "мирный", pos: "прил.", example: "A peaceful village." },
  crowded: { translation: "переполненный", pos: "прил.", example: "A crowded bus." },
  polluted: { translation: "загрязнённый", pos: "прил.", example: "Polluted air." },
  traffic: { translation: "движение", pos: "сущ.", example: "Heavy traffic." },
  building: { translation: "здание", pos: "сущ.", example: "A tall building." },
  neighbour: { translation: "сосед", pos: "сущ.", example: "Friendly neighbours." },

  // === Grade 7 / Module 2: Tale Time ===
  character: { translation: "персонаж", pos: "сущ.", example: "The main character is brave." },
  plot: { translation: "сюжет", pos: "сущ.", example: "The plot is exciting." },
  hero: { translation: "герой", pos: "сущ.", example: "He is the hero of the story." },
  villain: { translation: "злодей", pos: "сущ.", example: "The villain is clever." },
  adventure: { translation: "приключение", pos: "сущ.", example: "A great adventure begins." },
  "fairy tale": { translation: "сказка", pos: "сущ.", example: "Read a fairy tale." },
  novel: { translation: "роман", pos: "сущ.", example: "A long novel." },
  poem: { translation: "стихотворение", pos: "сущ.", example: "A short poem." },
  legend: { translation: "легенда", pos: "сущ.", example: "An old legend." },
  myth: { translation: "миф", pos: "сущ.", example: "Greek myth." },
  fiction: { translation: "художественная литература", pos: "сущ.", example: "Science fiction." },
  "non-fiction": { translation: "документальная литература", pos: "сущ.", example: "A non-fiction book." },
  narrator: { translation: "рассказчик", pos: "сущ.", example: "First-person narrator." },
  dialogue: { translation: "диалог", pos: "сущ.", example: "A short dialogue." },
  scene: { translation: "сцена", pos: "сущ.", example: "An emotional scene." },
  chapter: { translation: "глава", pos: "сущ.", example: "Chapter one." },
  page: { translation: "страница", pos: "сущ.", example: "Open page 12." },
  author: { translation: "автор", pos: "сущ.", example: "A famous author." },
  title: { translation: "название", pos: "сущ.", example: "What's the title?" },

  // === Grade 7 / Module 3: Profiles ===
  ambitious: { translation: "амбициозный", pos: "прил.", example: "An ambitious student." },
  creative: { translation: "творческий", pos: "прил.", example: "A creative mind." },
  loyal: { translation: "преданный", pos: "прил.", example: "A loyal friend." },
  generous: { translation: "щедрый", pos: "прил.", example: "A generous heart." },
  "hard-working": { translation: "трудолюбивый", pos: "прил.", example: "A hard-working employee." },
  talented: { translation: "талантливый", pos: "прил.", example: "Talented musician." },
  gifted: { translation: "одарённый", pos: "прил.", example: "A gifted child." },
  confident: { translation: "уверенный", pos: "прил.", example: "Confident speaker." },
  modest: { translation: "скромный", pos: "прил.", example: "Modest about success." },
  humble: { translation: "скромный", pos: "прил.", example: "A humble leader." },
  optimistic: { translation: "оптимистичный", pos: "прил.", example: "Optimistic outlook." },
  pessimistic: { translation: "пессимистичный", pos: "прил.", example: "Don't be pessimistic." },
  energetic: { translation: "энергичный", pos: "прил.", example: "An energetic puppy." },
  reliable: { translation: "надёжный", pos: "прил.", example: "A reliable friend." },
  stubborn: { translation: "упрямый", pos: "прил.", example: "Stubborn as a mule." },
  strict: { translation: "строгий", pos: "прил.", example: "A strict teacher." },
  sensitive: { translation: "чувствительный", pos: "прил.", example: "Sensitive to criticism." },

  // === Grade 7 / Module 4: In the News ===
  headline: { translation: "заголовок", pos: "сущ.", example: "Read the headline." },
  broadcast: { translation: "трансляция", pos: "сущ.", example: "Live broadcast from the stadium." },
  journalist: { translation: "журналист", pos: "сущ.", example: "She is a journalist." },
  report: { translation: "репортаж", pos: "сущ.", example: "Write a short report." },
  article: { translation: "статья", pos: "сущ.", example: "A newspaper article." },
  news: { translation: "новости", pos: "сущ.", example: "Watch the news at 9." },
  weather: { translation: "погода", pos: "сущ.", example: "Sunny weather." },
  interview: { translation: "интервью", pos: "сущ.", example: "Give an interview." },
  newspaper: { translation: "газета", pos: "сущ.", example: "Daily newspaper." },
  channel: { translation: "канал", pos: "сущ.", example: "Switch the channel." },
  anchor: { translation: "ведущий новостей", pos: "сущ.", example: "TV anchor." },
  microphone: { translation: "микрофон", pos: "сущ.", example: "Hold the microphone." },
  studio: { translation: "студия", pos: "сущ.", example: "Live from the studio." },
  "breaking news": { translation: "срочные новости", pos: "сущ.", example: "Breaking news report." },
  gossip: { translation: "сплетни", pos: "сущ.", example: "Don't spread gossip." },
  scandal: { translation: "скандал", pos: "сущ.", example: "A political scandal." },
  story: { translation: "история", pos: "сущ.", example: "A funny story." },
  source: { translation: "источник", pos: "сущ.", example: "Reliable source." },

  // === Grade 8 / Module 1: Socialising ===
  polite: { translation: "вежливый", pos: "прил.", example: "Be polite to elders." },
  rude: { translation: "грубый", pos: "прил.", example: "Don't be rude." },
  sociable: { translation: "общительный", pos: "прил.", example: "She is very sociable." },
  outgoing: { translation: "открытый", pos: "прил.", example: "He is outgoing and friendly." },
  introvert: { translation: "интроверт", pos: "сущ.", example: "I'm more of an introvert." },
  extrovert: { translation: "экстраверт", pos: "сущ.", example: "An extrovert loves people." },
  unfriendly: { translation: "недружелюбный", pos: "прил.", example: "An unfriendly stare." },
  formal: { translation: "официальный", pos: "прил.", example: "A formal suit." },
  informal: { translation: "неформальный", pos: "прил.", example: "An informal chat." },
  manners: { translation: "манеры", pos: "сущ.", example: "Good manners matter." },
  etiquette: { translation: "этикет", pos: "сущ.", example: "Business etiquette." },
  greeting: { translation: "приветствие", pos: "сущ.", example: "A friendly greeting." },
  handshake: { translation: "рукопожатие", pos: "сущ.", example: "Firm handshake." },
  gesture: { translation: "жест", pos: "сущ.", example: "A small gesture." },
  "body language": { translation: "язык тела", pos: "сущ.", example: "Read body language." },
  conversation: { translation: "разговор", pos: "сущ.", example: "An interesting conversation." },
  "small talk": { translation: "светская беседа", pos: "сущ.", example: "Make small talk." },
  communication: { translation: "общение", pos: "сущ.", example: "Effective communication." },

  // === Grade 8 / Module 2: Food & Shopping ===
  receipt: { translation: "чек", pos: "сущ.", example: "Keep your receipt." },
  discount: { translation: "скидка", pos: "сущ.", example: "A 20% discount." },
  refund: { translation: "возврат", pos: "сущ.", example: "I got a refund." },
  grocery: { translation: "продуктовый магазин", pos: "сущ.", example: "I go to the grocery." },
  boutique: { translation: "бутик", pos: "сущ.", example: "A small boutique." },
  supermarket: { translation: "супермаркет", pos: "сущ.", example: "Shop at the supermarket." },
  mall: { translation: "торговый центр", pos: "сущ.", example: "Meet me at the mall." },
  market: { translation: "рынок", pos: "сущ.", example: "Local market." },
  cashier: { translation: "кассир", pos: "сущ.", example: "Pay the cashier." },
  "shop assistant": { translation: "продавец-консультант", pos: "сущ.", example: "Ask the shop assistant." },
  customer: { translation: "клиент", pos: "сущ.", example: "A regular customer." },
  brand: { translation: "бренд", pos: "сущ.", example: "A famous brand." },
  label: { translation: "этикетка", pos: "сущ.", example: "Read the label." },
  price: { translation: "цена", pos: "сущ.", example: "What's the price?" },
  sale: { translation: "распродажа", pos: "сущ.", example: "Big summer sale." },
  bargain: { translation: "выгодная покупка", pos: "сущ.", example: "Real bargain." },
  queue: { translation: "очередь", pos: "сущ.", example: "Wait in the queue." },
  basket: { translation: "корзина", pos: "сущ.", example: "Take a basket." },
  trolley: { translation: "тележка", pos: "сущ.", example: "A shopping trolley." },
  change: { translation: "сдача / менять", pos: "гл./сущ.", example: "Keep the change." },

  // === Grade 8 / Module 3: Great Minds ===
  invention: { translation: "изобретение", pos: "сущ.", example: "A great invention." },
  discover: { translation: "открывать", pos: "гл.", example: "Columbus discovered America." },
  genius: { translation: "гений", pos: "сущ.", example: "Einstein was a genius." },
  breakthrough: { translation: "прорыв", pos: "сущ.", example: "A scientific breakthrough." },
  experiment: { translation: "эксперимент", pos: "сущ.", example: "Conduct an experiment." },
  scientist: { translation: "учёный", pos: "сущ.", example: "Famous scientist." },
  inventor: { translation: "изобретатель", pos: "сущ.", example: "Edison was an inventor." },
  philosopher: { translation: "философ", pos: "сущ.", example: "Ancient philosopher." },
  mathematician: { translation: "математик", pos: "сущ.", example: "A brilliant mathematician." },
  physicist: { translation: "физик", pos: "сущ.", example: "Theoretical physicist." },
  chemist: { translation: "химик", pos: "сущ.", example: "Lab chemist." },
  theory: { translation: "теория", pos: "сущ.", example: "A new theory." },
  formula: { translation: "формула", pos: "сущ.", example: "Mathematical formula." },
  laboratory: { translation: "лаборатория", pos: "сущ.", example: "Work in the laboratory." },
  microscope: { translation: "микроскоп", pos: "сущ.", example: "Look through the microscope." },
  telescope: { translation: "телескоп", pos: "сущ.", example: "Through the telescope." },
  technology: { translation: "технология", pos: "сущ.", example: "Modern technology." },
  research: { translation: "исследование", pos: "сущ.", example: "Carry out research." },
  knowledge: { translation: "знание", pos: "сущ.", example: "Useful knowledge." },
  evidence: { translation: "доказательство", pos: "сущ.", example: "Strong evidence." },

  // === Grade 8 / Module 4: Be Yourself ===
  outfit: { translation: "наряд", pos: "сущ.", example: "A cool outfit." },
  trendy: { translation: "модный", pos: "прил.", example: "Trendy sneakers." },
  baggy: { translation: "мешковатый", pos: "прил.", example: "Baggy jeans." },
  tight: { translation: "тесный", pos: "прил.", example: "Tight shoes hurt." },
  casual: { translation: "повседневный", pos: "прил.", example: "Casual style." },
  elegant: { translation: "элегантный", pos: "прил.", example: "An elegant dress." },
  stylish: { translation: "стильный", pos: "прил.", example: "Stylish jacket." },
  fashionable: { translation: "модный", pos: "прил.", example: "Fashionable trends." },
  jeans: { translation: "джинсы", pos: "сущ.", example: "Blue jeans." },
  jacket: { translation: "куртка", pos: "сущ.", example: "Warm jacket." },
  scarf: { translation: "шарф", pos: "сущ.", example: "A wool scarf." },
  gloves: { translation: "перчатки", pos: "сущ.", example: "Leather gloves." },
  boots: { translation: "сапоги", pos: "сущ.", example: "Winter boots." },
  sneakers: { translation: "кроссовки", pos: "сущ.", example: "White sneakers." },
  suit: { translation: "костюм", pos: "сущ.", example: "Business suit." },
  shirt: { translation: "рубашка", pos: "сущ.", example: "A white shirt." },
  "t-shirt": { translation: "футболка", pos: "сущ.", example: "Cotton t-shirt." },
  design: { translation: "дизайн", pos: "сущ.", example: "Modern design." },

  // === Extension modules 5–8 (Grades 2–8) ===
  // Grade 2: My Holidays / Food / Body / Going Places
  // (summer/winter/spring/autumn already defined in earlier modules)
  sunny: { translation: "солнечно", pos: "прил.", example: "It is sunny today." },
  rainy: { translation: "дождливо", pos: "прил.", example: "A rainy day." },
  snowy: { translation: "снежно", pos: "прил.", example: "A snowy morning." },
  cloudy: { translation: "облачно", pos: "прил.", example: "It's cloudy." },
  windy: { translation: "ветрено", pos: "прил.", example: "A windy day." },
  hot: { translation: "жарко", pos: "прил.", example: "It is hot." },
  cold: { translation: "холодно", pos: "прил.", example: "It's cold outside." },
  warm: { translation: "тепло", pos: "прил.", example: "A warm jacket." },
  umbrella: { translation: "зонт", pos: "сущ.", example: "Take an umbrella." },
  raincoat: { translation: "дождевик", pos: "сущ.", example: "A yellow raincoat." },
  sandals: { translation: "сандалии", pos: "сущ.", example: "Summer sandals." },
  hat: { translation: "шляпа", pos: "сущ.", example: "A red hat." },
  porridge: { translation: "каша", pos: "сущ.", example: "Hot porridge for breakfast." },
  yoghurt: { translation: "йогурт", pos: "сущ.", example: "Strawberry yoghurt." },
  cookie: { translation: "печенье", pos: "сущ.", example: "Chocolate cookie." },
  head: { translation: "голова", pos: "сущ.", example: "My head hurts." },
  ears: { translation: "уши", pos: "сущ.", example: "Big ears." },
  teeth: { translation: "зубы", pos: "сущ.", example: "Brush your teeth." },
  lips: { translation: "губы", pos: "сущ.", example: "Red lips." },
  tongue: { translation: "язык", pos: "сущ.", example: "Stick out your tongue." },
  neck: { translation: "шея", pos: "сущ.", example: "A long neck." },
  shoulder: { translation: "плечо", pos: "сущ.", example: "My shoulder hurts." },
  arm: { translation: "рука", pos: "сущ.", example: "Strong arm." },
  elbow: { translation: "локоть", pos: "сущ.", example: "Bend your elbow." },
  hand: { translation: "рука", pos: "сущ.", example: "Wash your hands." },
  finger: { translation: "палец", pos: "сущ.", example: "Index finger." },
  leg: { translation: "нога", pos: "сущ.", example: "Long legs." },
  knee: { translation: "колено", pos: "сущ.", example: "Sore knee." },
  foot: { translation: "стопа", pos: "сущ.", example: "Cold feet." },
  toe: { translation: "палец на ноге", pos: "сущ.", example: "Big toe." },
  back: { translation: "спина", pos: "сущ.", example: "Straight back." },
  park: { translation: "парк", pos: "сущ.", example: "Walk in the park." },
  shop: { translation: "магазин", pos: "сущ.", example: "A small shop." },
  museum: { translation: "музей", pos: "сущ.", example: "Art museum." },
  zoo: { translation: "зоопарк", pos: "сущ.", example: "Visit the zoo." },
  stadium: { translation: "стадион", pos: "сущ.", example: "Football stadium." },
  cinema: { translation: "кинотеатр", pos: "сущ.", example: "Go to the cinema." },
  cafe: { translation: "кафе", pos: "сущ.", example: "A cosy cafe." },
  playground: { translation: "детская площадка", pos: "сущ.", example: "Playground at school." },

  // Grade 3: Furry Friends / Home Sweet Home / Day Off / Day by Day
  dolphin: { translation: "дельфин", pos: "сущ.", example: "Dolphin swims fast." },
  whale: { translation: "кит", pos: "сущ.", example: "Blue whale." },
  fox: { translation: "лиса", pos: "сущ.", example: "Sly fox." },
  wolf: { translation: "волк", pos: "сущ.", example: "Grey wolf." },
  deer: { translation: "олень", pos: "сущ.", example: "Wild deer." },
  owl: { translation: "сова", pos: "сущ.", example: "Wise owl." },
  curtain: { translation: "штора", pos: "сущ.", example: "Open the curtains." },
  cupboard: { translation: "шкаф", pos: "сущ.", example: "Wooden cupboard." },
  drawer: { translation: "ящик", pos: "сущ.", example: "Top drawer." },
  ceiling: { translation: "потолок", pos: "сущ.", example: "High ceiling." },
  floor: { translation: "пол", pos: "сущ.", example: "Wooden floor." },
  wall: { translation: "стена", pos: "сущ.", example: "White wall." },
  fireplace: { translation: "камин", pos: "сущ.", example: "Cosy fireplace." },
  blanket: { translation: "одеяло", pos: "сущ.", example: "Warm blanket." },
  builder: { translation: "строитель", pos: "сущ.", example: "Skilled builder." },
  cook: { translation: "повар", pos: "сущ.", example: "Famous cook." },
  dancer: { translation: "танцор", pos: "сущ.", example: "Ballet dancer." },
  singer: { translation: "певец", pos: "сущ.", example: "Pop singer." },
  actor: { translation: "актёр", pos: "сущ.", example: "Movie actor." },
  writer: { translation: "писатель", pos: "сущ.", example: "Famous writer." },
  painter: { translation: "художник", pos: "сущ.", example: "A talented painter." },
  musician: { translation: "музыкант", pos: "сущ.", example: "Street musician." },
  always: { translation: "всегда", pos: "нар.", example: "I always read." },
  usually: { translation: "обычно", pos: "нар.", example: "We usually walk." },
  never: { translation: "никогда", pos: "нар.", example: "I never lie." },
  Monday: { translation: "понедельник", pos: "сущ.", example: "On Monday." },
  Tuesday: { translation: "вторник", pos: "сущ.", example: "Every Tuesday." },
  Wednesday: { translation: "среда", pos: "сущ.", example: "Wednesday morning." },
  Thursday: { translation: "четверг", pos: "сущ.", example: "Thursday class." },
  Friday: { translation: "пятница", pos: "сущ.", example: "Friday night." },
  Saturday: { translation: "суббота", pos: "сущ.", example: "Saturday off." },
  Sunday: { translation: "воскресенье", pos: "сущ.", example: "Sunday brunch." },
  morning: { translation: "утро", pos: "сущ.", example: "Good morning!" },
  afternoon: { translation: "день", pos: "сущ.", example: "This afternoon." },
  evening: { translation: "вечер", pos: "сущ.", example: "Quiet evening." },
  night: { translation: "ночь", pos: "сущ.", example: "Dark night." },
  midnight: { translation: "полночь", pos: "сущ.", example: "After midnight." },
  noon: { translation: "полдень", pos: "сущ.", example: "At noon." },
  today: { translation: "сегодня", pos: "нар.", example: "Today is sunny." },
  tomorrow: { translation: "завтра", pos: "нар.", example: "See you tomorrow." },
  yesterday: { translation: "вчера", pos: "нар.", example: "Yesterday was rainy." },
  early: { translation: "рано", pos: "нар.", example: "Wake up early." },
  late: { translation: "поздно", pos: "нар.", example: "It is late." },
  minute: { translation: "минута", pos: "сущ.", example: "One minute." },
  hour: { translation: "час", pos: "сущ.", example: "Half an hour." },

  // Grade 4: Where Were You / Tale Time / Days to Remember / Places to Go
  "last week": { translation: "на прошлой неделе", pos: "выр.", example: "We met last week." },
  "last year": { translation: "в прошлом году", pos: "выр.", example: "Last year I travelled." },
  ago: { translation: "тому назад", pos: "нар.", example: "A year ago." },
  then: { translation: "затем", pos: "нар.", example: "First eat, then play." },
  before: { translation: "до", pos: "пред.", example: "Before lunch." },
  after: { translation: "после", pos: "пред.", example: "After school." },
  during: { translation: "во время", pos: "пред.", example: "During the lesson." },
  "at home": { translation: "дома", pos: "выр.", example: "I stay at home." },
  "at school": { translation: "в школе", pos: "выр.", example: "We are at school." },
  "at the park": { translation: "в парке", pos: "выр.", example: "Kids at the park." },
  "at the beach": { translation: "на пляже", pos: "выр.", example: "Sunny at the beach." },
  "at the cinema": { translation: "в кинотеатре", pos: "выр.", example: "We met at the cinema." },
  "at the zoo": { translation: "в зоопарке", pos: "выр.", example: "Lions at the zoo." },
  shopping: { translation: "покупки", pos: "сущ.", example: "Go shopping." },
  bored: { translation: "скучно", pos: "прил.", example: "I am bored." },
  excited: { translation: "взволнованный", pos: "прил.", example: "Excited about the trip." },
  princess: { translation: "принцесса", pos: "сущ.", example: "Beautiful princess." },
  prince: { translation: "принц", pos: "сущ.", example: "Brave prince." },
  king: { translation: "король", pos: "сущ.", example: "The king." },
  queen: { translation: "королева", pos: "сущ.", example: "The queen." },
  wizard: { translation: "волшебник", pos: "сущ.", example: "Old wizard." },
  witch: { translation: "ведьма", pos: "сущ.", example: "Wicked witch." },
  fairy: { translation: "фея", pos: "сущ.", example: "Tiny fairy." },
  dragon: { translation: "дракон", pos: "сущ.", example: "Fire-breathing dragon." },
  castle: { translation: "замок", pos: "сущ.", example: "Old castle." },
  forest: { translation: "лес", pos: "сущ.", example: "Dark forest." },
  monster: { translation: "монстр", pos: "сущ.", example: "Scary monster." },
  magic: { translation: "магия", pos: "сущ.", example: "Powerful magic." },
  treasure: { translation: "сокровище", pos: "сущ.", example: "Hidden treasure." },
  spell: { translation: "заклинание", pos: "сущ.", example: "Cast a spell." },
  began: { translation: "начал", pos: "глаг.", example: "She began to sing." },
  went: { translation: "пошёл", pos: "глаг.", example: "We went home." },
  saw: { translation: "увидел", pos: "глаг.", example: "I saw a deer." },
  took: { translation: "взял", pos: "глаг.", example: "He took the book." },
  ran: { translation: "побежал", pos: "глаг.", example: "She ran fast." },
  wedding: { translation: "свадьба", pos: "сущ.", example: "Beautiful wedding." },
  concert: { translation: "концерт", pos: "сущ.", example: "Rock concert." },
  carnival: { translation: "карнавал", pos: "сущ.", example: "Brazilian carnival." },
  reunion: { translation: "встреча выпускников", pos: "сущ.", example: "Family reunion." },
  graduation: { translation: "выпускной", pos: "сущ.", example: "Graduation day." },
  memory: { translation: "память", pos: "сущ.", example: "Happy memory." },
  diary: { translation: "дневник", pos: "сущ.", example: "Secret diary." },
  album: { translation: "альбом", pos: "сущ.", example: "Photo album." },
  remember: { translation: "помнить", pos: "глаг.", example: "I remember you." },
  forget: { translation: "забывать", pos: "глаг.", example: "Don't forget!" },
  wish: { translation: "желание", pos: "сущ.", example: "Make a wish." },
  dream: { translation: "мечта", pos: "сущ.", example: "Big dream." },
  beach: { translation: "пляж", pos: "сущ.", example: "Sandy beach." },
  mountain: { translation: "гора", pos: "сущ.", example: "Tall mountain." },
  lake: { translation: "озеро", pos: "сущ.", example: "Quiet lake." },
  river: { translation: "река", pos: "сущ.", example: "Fast river." },
  desert: { translation: "пустыня", pos: "сущ.", example: "Hot desert." },
  island: { translation: "остров", pos: "сущ.", example: "Tropical island." },
  valley: { translation: "долина", pos: "сущ.", example: "Green valley." },
  hill: { translation: "холм", pos: "сущ.", example: "Up the hill." },
  ocean: { translation: "океан", pos: "сущ.", example: "Pacific ocean." },
  ticket: { translation: "билет", pos: "сущ.", example: "Train ticket." },
  luggage: { translation: "багаж", pos: "сущ.", example: "Heavy luggage." },
  hotel: { translation: "отель", pos: "сущ.", example: "Five-star hotel." },
  tent: { translation: "палатка", pos: "сущ.", example: "Camping tent." },
  sunbathe: { translation: "загорать", pos: "глаг.", example: "Sunbathe at the beach." },
  explore: { translation: "исследовать", pos: "глаг.", example: "Explore the city." },
  camp: { translation: "лагерь", pos: "сущ.", example: "Summer camp." },
  hike: { translation: "поход", pos: "сущ.", example: "Mountain hike." },

  // Grade 5: World Animals / Round the Clock / In all Weathers / Special Days
  habitat: { translation: "среда обитания", pos: "сущ.", example: "Forest habitat." },
  endangered: { translation: "находящийся под угрозой", pos: "прил.", example: "Endangered species." },
  predator: { translation: "хищник", pos: "сущ.", example: "Apex predator." },
  prey: { translation: "добыча", pos: "сущ.", example: "Easy prey." },
  wildlife: { translation: "дикая природа", pos: "сущ.", example: "African wildlife." },
  savannah: { translation: "саванна", pos: "сущ.", example: "On the savannah." },
  jungle: { translation: "джунгли", pos: "сущ.", example: "Amazon jungle." },
  polar: { translation: "полярный", pos: "прил.", example: "Polar bear." },
  tropical: { translation: "тропический", pos: "прил.", example: "Tropical forest." },
  mammal: { translation: "млекопитающее", pos: "сущ.", example: "Whales are mammals." },
  reptile: { translation: "рептилия", pos: "сущ.", example: "Cold-blooded reptile." },
  insect: { translation: "насекомое", pos: "сущ.", example: "Tiny insect." },
  amphibian: { translation: "земноводное", pos: "сущ.", example: "Frog is an amphibian." },
  claw: { translation: "коготь", pos: "сущ.", example: "Sharp claw." },
  schedule: { translation: "расписание", pos: "сущ.", example: "Busy schedule." },
  appointment: { translation: "приём, встреча", pos: "сущ.", example: "Doctor appointment." },
  deadline: { translation: "срок сдачи", pos: "сущ.", example: "Strict deadline." },
  alarm: { translation: "будильник", pos: "сущ.", example: "Set the alarm." },
  second: { translation: "секунда", pos: "сущ.", example: "Wait a second." },
  "quarter past": { translation: "пятнадцать минут после", pos: "выр.", example: "Quarter past three." },
  "half past": { translation: "половина", pos: "выр.", example: "Half past two." },
  "quarter to": { translation: "без четверти", pos: "выр.", example: "Quarter to five." },
  "get dressed": { translation: "одеваться", pos: "глаг.", example: "Get dressed quickly." },
  "have breakfast": { translation: "завтракать", pos: "глаг.", example: "Have breakfast at 8." },
  "leave home": { translation: "выйти из дома", pos: "выр.", example: "Leave home at seven." },
  currently: { translation: "сейчас", pos: "нар.", example: "Currently studying." },
  "right now": { translation: "прямо сейчас", pos: "выр.", example: "Right now I'm busy." },
  "at the moment": { translation: "в данный момент", pos: "выр.", example: "Busy at the moment." },
  "this week": { translation: "на этой неделе", pos: "выр.", example: "Test this week." },
  thunderstorm: { translation: "гроза", pos: "сущ.", example: "Heavy thunderstorm." },
  lightning: { translation: "молния", pos: "сущ.", example: "Bright lightning." },
  blizzard: { translation: "метель", pos: "сущ.", example: "Snow blizzard." },
  hurricane: { translation: "ураган", pos: "сущ.", example: "Tropical hurricane." },
  drought: { translation: "засуха", pos: "сущ.", example: "Long drought." },
  humid: { translation: "влажный", pos: "прил.", example: "Humid air." },
  freezing: { translation: "ледяной", pos: "прил.", example: "Freezing wind." },
  boiling: { translation: "кипящий", pos: "прил.", example: "Boiling hot." },
  mild: { translation: "мягкий", pos: "прил.", example: "Mild weather." },
  stormy: { translation: "штормовой", pos: "прил.", example: "Stormy night." },
  forecast: { translation: "прогноз", pos: "сущ.", example: "Weather forecast." },
  temperature: { translation: "температура", pos: "сущ.", example: "High temperature." },
  degree: { translation: "градус / диплом", pos: "сущ.", example: "Twenty degrees." },
  climate: { translation: "климат", pos: "сущ.", example: "Mild climate." },
  atmosphere: { translation: "атмосфера", pos: "сущ.", example: "Friendly atmosphere." },
  rainbow: { translation: "радуга", pos: "сущ.", example: "Beautiful rainbow." },
  fog: { translation: "туман", pos: "сущ.", example: "Thick fog." },
  frost: { translation: "иней", pos: "сущ.", example: "Morning frost." },
  hail: { translation: "град", pos: "сущ.", example: "Heavy hail." },
  breeze: { translation: "ветерок", pos: "сущ.", example: "Sea breeze." },
  celebrate: { translation: "праздновать", pos: "глаг.", example: "Celebrate birthday." },
  tradition: { translation: "традиция", pos: "сущ.", example: "Family tradition." },
  custom: { translation: "обычай", pos: "сущ.", example: "Old custom." },
  decorate: { translation: "украшать", pos: "глаг.", example: "Decorate the tree." },
  invite: { translation: "пригласить", pos: "глаг.", example: "Invite friends." },
  gift: { translation: "подарок", pos: "сущ.", example: "Birthday gift." },
  ribbon: { translation: "лента", pos: "сущ.", example: "Red ribbon." },
  candle: { translation: "свеча", pos: "сущ.", example: "Light a candle." },
  fireworks: { translation: "фейерверк", pos: "сущ.", example: "New Year fireworks." },
  parade: { translation: "парад", pos: "сущ.", example: "Big parade." },
  costume: { translation: "костюм", pos: "сущ.", example: "Funny costume." },
  mask: { translation: "маска", pos: "сущ.", example: "Halloween mask." },
  Christmas: { translation: "Рождество", pos: "сущ.", example: "Merry Christmas." },
  Easter: { translation: "Пасха", pos: "сущ.", example: "Easter eggs." },
  Halloween: { translation: "Хэллоуин", pos: "сущ.", example: "Halloween party." },
  Thanksgiving: { translation: "День Благодарения", pos: "сущ.", example: "Thanksgiving turkey." },
  "New Year": { translation: "Новый Год", pos: "сущ.", example: "Happy New Year!" },

  // Grade 6: Feasts / Leisure / Now and Then / Rules
  feast: { translation: "пир", pos: "сущ.", example: "Royal feast." },
  banquet: { translation: "банкет", pos: "сущ.", example: "Wedding banquet." },
  gathering: { translation: "собрание", pos: "сущ.", example: "Family gathering." },
  ritual: { translation: "ритуал", pos: "сущ.", example: "Morning ritual." },
  lantern: { translation: "фонарь", pos: "сущ.", example: "Paper lantern." },
  barbecue: { translation: "барбекю", pos: "сущ.", example: "Garden barbecue." },
  picnic: { translation: "пикник", pos: "сущ.", example: "Sunday picnic." },
  buffet: { translation: "шведский стол", pos: "сущ.", example: "Hotel buffet." },
  dumpling: { translation: "пельмень", pos: "сущ.", example: "Steamed dumpling." },
  pancake: { translation: "блин", pos: "сущ.", example: "Sweet pancake." },
  pumpkin: { translation: "тыква", pos: "сущ.", example: "Pumpkin pie." },
  turkey: { translation: "индейка", pos: "сущ.", example: "Roast turkey." },
  spice: { translation: "специя", pos: "сущ.", example: "Indian spice." },
  guest: { translation: "гость", pos: "сущ.", example: "Welcome the guest." },
  host: { translation: "хозяин", pos: "сущ.", example: "Friendly host." },
  toast: { translation: "тост", pos: "сущ.", example: "Make a toast." },
  speech: { translation: "речь", pos: "сущ.", example: "Short speech." },
  menu: { translation: "меню", pos: "сущ.", example: "Read the menu." },
  skateboarding: { translation: "скейтбординг", pos: "сущ.", example: "Love skateboarding." },
  surfing: { translation: "сёрфинг", pos: "сущ.", example: "Hawaii surfing." },
  "rock climbing": { translation: "скалолазание", pos: "выр.", example: "Rock climbing club." },
  diving: { translation: "дайвинг", pos: "сущ.", example: "Scuba diving." },
  cycling: { translation: "велоспорт", pos: "сущ.", example: "Daily cycling." },
  hiking: { translation: "пеший туризм", pos: "сущ.", example: "Mountain hiking." },
  camping: { translation: "кемпинг", pos: "сущ.", example: "Forest camping." },
  fishing: { translation: "рыбалка", pos: "сущ.", example: "River fishing." },
  gardening: { translation: "садоводство", pos: "сущ.", example: "Spring gardening." },
  knitting: { translation: "вязание", pos: "сущ.", example: "Grandma's knitting." },
  photography: { translation: "фотография", pos: "сущ.", example: "Wildlife photography." },
  cards: { translation: "карты", pos: "сущ.", example: "Play cards." },
  "free time": { translation: "свободное время", pos: "выр.", example: "In my free time." },
  leisure: { translation: "досуг", pos: "сущ.", example: "Leisure activity." },
  vacation: { translation: "отпуск", pos: "сущ.", example: "Summer vacation." },
  ancient: { translation: "древний", pos: "прил.", example: "Ancient city." },
  modern: { translation: "современный", pos: "прил.", example: "Modern art." },
  era: { translation: "эпоха", pos: "сущ.", example: "Victorian era." },
  historic: { translation: "исторический", pos: "прил.", example: "Historic event." },
  vintage: { translation: "винтажный", pos: "прил.", example: "Vintage car." },
  antique: { translation: "антикварный", pos: "прил.", example: "Antique clock." },
  futuristic: { translation: "футуристический", pos: "прил.", example: "Futuristic design." },
  outdated: { translation: "устаревший", pos: "прил.", example: "Outdated phone." },
  discovery: { translation: "открытие", pos: "сущ.", example: "Great discovery." },
  progress: { translation: "прогресс", pos: "сущ.", example: "Steady progress." },
  ancestor: { translation: "предок", pos: "сущ.", example: "Distant ancestor." },
  descendant: { translation: "потомок", pos: "сущ.", example: "Direct descendant." },
  generation: { translation: "поколение", pos: "сущ.", example: "Older generation." },
  heritage: { translation: "наследие", pos: "сущ.", example: "Cultural heritage." },
  "great-grandparent": { translation: "прадедушка/прабабушка", pos: "сущ.", example: "My great-grandparent." },
  rule: { translation: "правило", pos: "сущ.", example: "Strict rule." },
  law: { translation: "закон", pos: "сущ.", example: "Local law." },
  regulation: { translation: "регламент", pos: "сущ.", example: "Safety regulation." },
  permission: { translation: "разрешение", pos: "сущ.", example: "Ask for permission." },
  warning: { translation: "предупреждение", pos: "сущ.", example: "Final warning." },
  punishment: { translation: "наказание", pos: "сущ.", example: "Light punishment." },
  fine: { translation: "штраф", pos: "сущ.", example: "Pay the fine." },
  detention: { translation: "оставление после уроков", pos: "сущ.", example: "Got detention." },
  behaviour: { translation: "поведение", pos: "сущ.", example: "Good behaviour." },
  must: { translation: "должен", pos: "мод.", example: "I must go." },
  "have to": { translation: "должен", pos: "мод.", example: "I have to study." },
  should: { translation: "следует", pos: "мод.", example: "You should rest." },
  "ought to": { translation: "следовало бы", pos: "мод.", example: "We ought to help." },
  "be allowed to": { translation: "разрешено", pos: "выр.", example: "Allowed to enter." },
  obey: { translation: "подчиняться", pos: "глаг.", example: "Obey the rules." },
  "break the rule": { translation: "нарушить правило", pos: "выр.", example: "Don't break the rule." },
  respect: { translation: "уважение", pos: "сущ.", example: "Respect for elders." },
  discipline: { translation: "дисциплина", pos: "сущ.", example: "Strict discipline." },

  // Grade 7: Future / Having Fun / Spotlight / Green Issues
  spaceship: { translation: "космический корабль", pos: "сущ.", example: "Mars spaceship." },
  colony: { translation: "колония", pos: "сущ.", example: "Mars colony." },
  predict: { translation: "предсказывать", pos: "глаг.", example: "Predict the future." },
  "artificial intelligence": { translation: "искусственный интеллект", pos: "выр.", example: "Modern AI." },
  "virtual reality": { translation: "виртуальная реальность", pos: "выр.", example: "VR headset." },
  drone: { translation: "дрон", pos: "сущ.", example: "Camera drone." },
  "smart device": { translation: "умное устройство", pos: "выр.", example: "New smart device." },
  automation: { translation: "автоматизация", pos: "сущ.", example: "Factory automation." },
  renewable: { translation: "возобновляемый", pos: "прил.", example: "Renewable energy." },
  sustainable: { translation: "устойчивый", pos: "прил.", example: "Sustainable living." },
  "eco-friendly": { translation: "экологичный", pos: "прил.", example: "Eco-friendly bag." },
  innovation: { translation: "инновация", pos: "сущ.", example: "Tech innovation." },
  engineer: { translation: "инженер", pos: "сущ.", example: "Software engineer." },
  "amusement park": { translation: "парк аттракционов", pos: "выр.", example: "Big amusement park." },
  "roller coaster": { translation: "американские горки", pos: "выр.", example: "Tall roller coaster." },
  crowd: { translation: "толпа", pos: "сущ.", example: "Big crowd." },
  attraction: { translation: "аттракцион", pos: "сущ.", example: "Main attraction." },
  ride: { translation: "поездка", pos: "сущ.", example: "Fun ride." },
  performance: { translation: "выступление", pos: "сущ.", example: "Live performance." },
  show: { translation: "шоу", pos: "сущ.", example: "TV show." },
  comedy: { translation: "комедия", pos: "сущ.", example: "Stand-up comedy." },
  drama: { translation: "драма", pos: "сущ.", example: "Romantic drama." },
  stage: { translation: "сцена", pos: "сущ.", example: "On the stage." },
  audience: { translation: "зрители", pos: "сущ.", example: "Big audience." },
  applause: { translation: "аплодисменты", pos: "сущ.", example: "Loud applause." },
  "theme park": { translation: "тематический парк", pos: "выр.", example: "Disney theme park." },
  fair: { translation: "ярмарка", pos: "сущ.", example: "Local fair." },
  circus: { translation: "цирк", pos: "сущ.", example: "Travelling circus." },
  celebrity: { translation: "знаменитость", pos: "сущ.", example: "TV celebrity." },
  actress: { translation: "актриса", pos: "сущ.", example: "Famous actress." },
  director: { translation: "режиссёр", pos: "сущ.", example: "Film director." },
  producer: { translation: "продюсер", pos: "сущ.", example: "Music producer." },
  fan: { translation: "фанат", pos: "сущ.", example: "Loyal fan." },
  fame: { translation: "слава", pos: "сущ.", example: "Sudden fame." },
  talent: { translation: "талант", pos: "сущ.", example: "Natural talent." },
  rehearsal: { translation: "репетиция", pos: "сущ.", example: "Final rehearsal." },
  soundtrack: { translation: "саундтрек", pos: "сущ.", example: "Movie soundtrack." },
  lyrics: { translation: "слова песни", pos: "сущ.", example: "Catchy lyrics." },
  melody: { translation: "мелодия", pos: "сущ.", example: "Sweet melody." },
  rhythm: { translation: "ритм", pos: "сущ.", example: "Steady rhythm." },
  blockbuster: { translation: "блокбастер", pos: "сущ.", example: "Summer blockbuster." },
  premiere: { translation: "премьера", pos: "сущ.", example: "World premiere." },
  review: { translation: "обзор", pos: "сущ.", example: "Movie review." },
  rating: { translation: "рейтинг", pos: "сущ.", example: "Five-star rating." },
  award: { translation: "награда", pos: "сущ.", example: "Best film award." },
  pollution: { translation: "загрязнение", pos: "сущ.", example: "Air pollution." },
  recycling: { translation: "переработка", pos: "сущ.", example: "Plastic recycling." },
  "global warming": { translation: "глобальное потепление", pos: "выр.", example: "Stop global warming." },
  "climate change": { translation: "изменение климата", pos: "выр.", example: "Climate change is real." },
  deforestation: { translation: "вырубка лесов", pos: "сущ.", example: "Tropical deforestation." },
  extinction: { translation: "вымирание", pos: "сущ.", example: "Mass extinction." },
  ecosystem: { translation: "экосистема", pos: "сущ.", example: "Marine ecosystem." },
  biodiversity: { translation: "биоразнообразие", pos: "сущ.", example: "Save biodiversity." },
  organic: { translation: "органический", pos: "прил.", example: "Organic food." },
  compost: { translation: "компост", pos: "сущ.", example: "Garden compost." },
  litter: { translation: "мусор", pos: "сущ.", example: "Pick up the litter." },
  save: { translation: "спасать", pos: "глаг.", example: "Save the planet." },
  protect: { translation: "защищать", pos: "глаг.", example: "Protect nature." },
  reduce: { translation: "сокращать", pos: "глаг.", example: "Reduce waste." },
  reuse: { translation: "повторно использовать", pos: "глаг.", example: "Reuse bottles." },
  preserve: { translation: "сохранять", pos: "глаг.", example: "Preserve forests." },

  // Grade 8: Global Issues / Culture / Education / Pastimes
  earthquake: { translation: "землетрясение", pos: "сущ.", example: "Strong earthquake." },
  volcano: { translation: "вулкан", pos: "сущ.", example: "Active volcano." },
  tsunami: { translation: "цунами", pos: "сущ.", example: "Tsunami warning." },
  tornado: { translation: "торнадо", pos: "сущ.", example: "Texas tornado." },
  flood: { translation: "наводнение", pos: "сущ.", example: "Spring flood." },
  wildfire: { translation: "лесной пожар", pos: "сущ.", example: "California wildfire." },
  avalanche: { translation: "лавина", pos: "сущ.", example: "Mountain avalanche." },
  landslide: { translation: "оползень", pos: "сущ.", example: "Heavy landslide." },
  cyclone: { translation: "циклон", pos: "сущ.", example: "Tropical cyclone." },
  rescue: { translation: "спасать", pos: "глаг.", example: "Rescue team." },
  shelter: { translation: "укрытие", pos: "сущ.", example: "Emergency shelter." },
  aid: { translation: "помощь", pos: "сущ.", example: "Humanitarian aid." },
  donation: { translation: "пожертвование", pos: "сущ.", example: "Anonymous donation." },
  volunteer: { translation: "доброволец", pos: "сущ.", example: "Active volunteer." },
  charity: { translation: "благотворительность", pos: "сущ.", example: "Local charity." },
  crisis: { translation: "кризис", pos: "сущ.", example: "Economic crisis." },
  emergency: { translation: "чрезвычайная ситуация", pos: "сущ.", example: "Call emergency." },
  evacuation: { translation: "эвакуация", pos: "сущ.", example: "Quick evacuation." },
  victim: { translation: "жертва", pos: "сущ.", example: "Help the victims." },
  tourist: { translation: "турист", pos: "сущ.", example: "Foreign tourist." },
  guide: { translation: "гид", pos: "сущ.", example: "Local guide." },
  souvenir: { translation: "сувенир", pos: "сущ.", example: "Buy a souvenir." },
  landmark: { translation: "достопримечательность", pos: "сущ.", example: "Famous landmark." },
  monument: { translation: "памятник", pos: "сущ.", example: "Marble monument." },
  destination: { translation: "пункт назначения", pos: "сущ.", example: "Holiday destination." },
  itinerary: { translation: "маршрут", pos: "сущ.", example: "Travel itinerary." },
  sightseeing: { translation: "осмотр достопримечательностей", pos: "сущ.", example: "City sightseeing." },
  tour: { translation: "экскурсия", pos: "сущ.", example: "Walking tour." },
  excursion: { translation: "экскурсия", pos: "сущ.", example: "School excursion." },
  taboo: { translation: "табу", pos: "сущ.", example: "Cultural taboo." },
  bilingual: { translation: "двуязычный", pos: "прил.", example: "Bilingual school." },
  translate: { translation: "переводить", pos: "глаг.", example: "Translate the text." },
  interpret: { translation: "истолковывать", pos: "глаг.", example: "Interpret a dream." },
  fluent: { translation: "беглый", pos: "прил.", example: "Fluent English." },
  accent: { translation: "акцент", pos: "сущ.", example: "Strong accent." },
  university: { translation: "университет", pos: "сущ.", example: "Famous university." },
  college: { translation: "колледж", pos: "сущ.", example: "Local college." },
  scholarship: { translation: "стипендия", pos: "сущ.", example: "Full scholarship." },
  lecture: { translation: "лекция", pos: "сущ.", example: "Boring lecture." },
  seminar: { translation: "семинар", pos: "сущ.", example: "Weekly seminar." },
  tutorial: { translation: "семинар (малая группа)", pos: "сущ.", example: "Group tutorial." },
  thesis: { translation: "диссертация", pos: "сущ.", example: "Defend a thesis." },
  test: { translation: "тест", pos: "сущ.", example: "Hard test." },
  quiz: { translation: "викторина", pos: "сущ.", example: "Surprise quiz." },
  essay: { translation: "эссе", pos: "сущ.", example: "Short essay." },
  project: { translation: "проект", pos: "сущ.", example: "Group project." },
  graduate: { translation: "выпускник", pos: "сущ.", example: "Recent graduate." },
  undergraduate: { translation: "студент-бакалавр", pos: "сущ.", example: "Undergraduate student." },
  professor: { translation: "профессор", pos: "сущ.", example: "Strict professor." },
  academic: { translation: "академический", pos: "прил.", example: "Academic year." },
  campus: { translation: "кампус", pos: "сущ.", example: "Big campus." },
  fitness: { translation: "фитнес", pos: "сущ.", example: "Fitness club." },
  workout: { translation: "тренировка", pos: "сущ.", example: "Daily workout." },
  stamina: { translation: "выносливость", pos: "сущ.", example: "Build stamina." },
  strength: { translation: "сила", pos: "сущ.", example: "Inner strength." },
  flexibility: { translation: "гибкость", pos: "сущ.", example: "Improve flexibility." },
  yoga: { translation: "йога", pos: "сущ.", example: "Morning yoga." },
  pilates: { translation: "пилатес", pos: "сущ.", example: "Pilates class." },
  aerobics: { translation: "аэробика", pos: "сущ.", example: "Step aerobics." },
  marathon: { translation: "марафон", pos: "сущ.", example: "Run a marathon." },
  triathlon: { translation: "триатлон", pos: "сущ.", example: "Triathlon athlete." },
  diet: { translation: "диета", pos: "сущ.", example: "Healthy diet." },
  nutrition: { translation: "питание", pos: "сущ.", example: "Balanced nutrition." },
  calorie: { translation: "калория", pos: "сущ.", example: "Count calories." },
  vitamin: { translation: "витамин", pos: "сущ.", example: "Vitamin C." },
  protein: { translation: "белок", pos: "сущ.", example: "High protein." },
  pastime: { translation: "хобби", pos: "сущ.", example: "Favourite pastime." },
  passion: { translation: "страсть", pos: "сущ.", example: "Music is my passion." },
  enthusiast: { translation: "энтузиаст", pos: "сущ.", example: "Sports enthusiast." },
  addicted: { translation: "зависимый", pos: "прил.", example: "Addicted to games." },

  // === Grade 5 / Module 9: Modern Living ===
  "shopping centre": { translation: "торговый центр", pos: "сущ.", example: "Meet at the shopping centre." },
  "department store": { translation: "универмаг", pos: "сущ.", example: "A big department store." },
  bakery: { translation: "пекарня", pos: "сущ.", example: "Fresh bread at the bakery." },
  "butcher's": { translation: "мясная лавка", pos: "сущ.", example: "Buy meat at the butcher's." },
  florist: { translation: "цветочный магазин", pos: "сущ.", example: "Roses from the florist." },
  newsagent: { translation: "газетный киоск", pos: "сущ.", example: "Buy a paper at the newsagent." },
  kiosk: { translation: "киоск", pos: "сущ.", example: "Snacks at the kiosk." },
  voucher: { translation: "купон", pos: "сущ.", example: "Use a discount voucher." },
  checkout: { translation: "касса", pos: "сущ.", example: "Long queue at the checkout." },
  delivery: { translation: "доставка", pos: "сущ.", example: "Free delivery on orders." },

  // === Grade 5 / Module 10: Holidays ===
  resort: { translation: "курорт", pos: "сущ.", example: "A seaside resort." },
  mountains: { translation: "горы", pos: "сущ.", example: "Skiing in the mountains." },
  "package tour": { translation: "путёвка", pos: "сущ.", example: "Book a package tour." },
  cruise: { translation: "круиз", pos: "сущ.", example: "A Mediterranean cruise." },
  safari: { translation: "сафари", pos: "сущ.", example: "Go on safari in Kenya." },
  suitcase: { translation: "чемодан", pos: "сущ.", example: "Pack your suitcase." },
  backpack: { translation: "рюкзак", pos: "сущ.", example: "A heavy backpack." },
  visa: { translation: "виза", pos: "сущ.", example: "Apply for a visa." },
  "boarding pass": { translation: "посадочный талон", pos: "сущ.", example: "Show your boarding pass." },
  postcard: { translation: "открытка", pos: "сущ.", example: "Send a postcard from Paris." },
  experience: { translation: "опыт", pos: "сущ.", example: "An amazing experience." },
  journey: { translation: "путешествие", pos: "сущ.", example: "A long journey home." },

  // === Grade 6 / Module 9: Food & Refreshments ===
  starter: { translation: "закуска", pos: "сущ.", example: "Soup as a starter." },
  "main course": { translation: "основное блюдо", pos: "сущ.", example: "Steak as the main course." },
  dessert: { translation: "десерт", pos: "сущ.", example: "Ice cream for dessert." },
  "side dish": { translation: "гарнир", pos: "сущ.", example: "Rice as a side dish." },
  appetizer: { translation: "закуска", pos: "сущ.", example: "A light appetizer." },
  snack: { translation: "перекус", pos: "сущ.", example: "Have a quick snack." },
  spicy: { translation: "острый", pos: "прил.", example: "Spicy curry." },
  salty: { translation: "солёный", pos: "прил.", example: "Salty chips." },
  sour: { translation: "кислый", pos: "прил.", example: "Sour lemons." },
  bitter: { translation: "горький", pos: "прил.", example: "Bitter chocolate." },
  waitress: { translation: "официантка", pos: "сущ.", example: "The waitress took our order." },
  chef: { translation: "шеф-повар", pos: "сущ.", example: "A famous chef." },
  tip: { translation: "чаевые", pos: "сущ.", example: "Leave a tip." },
  bill: { translation: "счёт", pos: "сущ.", example: "Pay the bill." },

  // === Grade 6 / Module 10: Holiday Time ===
  booking: { translation: "бронь", pos: "сущ.", example: "Confirm the booking." },
  reservation: { translation: "бронирование", pos: "сущ.", example: "Make a reservation online." },
  "check-in": { translation: "регистрация заезда", pos: "сущ.", example: "Check-in is at 3 pm." },
  "check-out": { translation: "выезд", pos: "сущ.", example: "Check-out before noon." },
  receptionist: { translation: "администратор", pos: "сущ.", example: "Ask the receptionist." },
  "single room": { translation: "одноместный номер", pos: "сущ.", example: "Book a single room." },
  "double room": { translation: "двухместный номер", pos: "сущ.", example: "A double room with a balcony." },
  suite: { translation: "люкс", pos: "сущ.", example: "Honeymoon suite." },
  balcony: { translation: "балкон", pos: "сущ.", example: "A sea-view balcony." },
  view: { translation: "вид", pos: "сущ.", example: "What a beautiful view!" },
  "all-inclusive": { translation: "всё включено", pos: "прил.", example: "An all-inclusive resort." },
  "half-board": { translation: "полупансион", pos: "сущ.", example: "We chose half-board." },
  "self-catering": { translation: "самостоятельное питание", pos: "сущ.", example: "A self-catering apartment." },
  currency: { translation: "валюта", pos: "сущ.", example: "The local currency is the euro." },
  "exchange rate": { translation: "курс обмена", pos: "сущ.", example: "Check the exchange rate." },
  guidebook: { translation: "путеводитель", pos: "сущ.", example: "A guidebook to Rome." },
  map: { translation: "карта", pos: "сущ.", example: "Open the map." },
  compass: { translation: "компас", pos: "сущ.", example: "Take a compass on the hike." },
  binoculars: { translation: "бинокль", pos: "сущ.", example: "Binoculars for bird-watching." },

  // === Grade 7 / Module 9: Shopping Time ===
  advertisement: { translation: "реклама", pos: "сущ.", example: "A TV advertisement." },
  commercial: { translation: "ролик", pos: "сущ.", example: "A funny commercial." },
  logo: { translation: "логотип", pos: "сущ.", example: "A famous logo." },
  slogan: { translation: "слоган", pos: "сущ.", example: "Catchy slogan." },
  consumer: { translation: "потребитель", pos: "сущ.", example: "Consumer rights." },
  client: { translation: "клиент", pos: "сущ.", example: "An important client." },
  supplier: { translation: "поставщик", pos: "сущ.", example: "Trusted supplier." },
  retailer: { translation: "ритейлер", pos: "сущ.", example: "Online retailer." },
  afford: { translation: "позволить себе", pos: "гл.", example: "I can't afford it." },
  spend: { translation: "тратить", pos: "гл.", example: "Spend money wisely." },
  borrow: { translation: "брать в долг", pos: "гл.", example: "Borrow a book." },
  lend: { translation: "одолжить", pos: "гл.", example: "Lend me a pen." },
  expensive: { translation: "дорогой", pos: "прил.", example: "An expensive watch." },
  cheap: { translation: "дешёвый", pos: "прил.", example: "Cheap flights." },
  affordable: { translation: "доступный", pos: "прил.", example: "Affordable prices." },
  valuable: { translation: "ценный", pos: "прил.", example: "A valuable lesson." },
  priceless: { translation: "бесценный", pos: "прил.", example: "A priceless painting." },

  // === Grade 7 / Module 10: Healthy Body, Healthy Mind ===
  headache: { translation: "головная боль", pos: "сущ.", example: "I have a headache." },
  toothache: { translation: "зубная боль", pos: "сущ.", example: "Bad toothache." },
  stomachache: { translation: "боль в животе", pos: "сущ.", example: "Stomachache after lunch." },
  backache: { translation: "боль в спине", pos: "сущ.", example: "Backache from sitting." },
  earache: { translation: "боль в ухе", pos: "сущ.", example: "Earache and a cold." },
  cough: { translation: "кашель", pos: "сущ.", example: "A dry cough." },
  sneeze: { translation: "чихание", pos: "сущ.", example: "Cover your sneeze." },
  fever: { translation: "температура", pos: "сущ.", example: "High fever." },
  rash: { translation: "сыпь", pos: "сущ.", example: "An itchy rash." },
  injury: { translation: "травма", pos: "сущ.", example: "A sports injury." },
  stress: { translation: "стресс", pos: "сущ.", example: "Manage stress." },
  anxiety: { translation: "тревога", pos: "сущ.", example: "Exam anxiety." },
  relaxation: { translation: "расслабление", pos: "сущ.", example: "Relaxation techniques." },
  meditation: { translation: "медитация", pos: "сущ.", example: "Daily meditation." },
  balance: { translation: "баланс", pos: "сущ.", example: "Work-life balance." },
  recover: { translation: "выздоравливать", pos: "гл.", example: "Recover quickly." },
  heal: { translation: "лечить", pos: "гл.", example: "Time heals." },
  treat: { translation: "лечить", pos: "гл.", example: "Treat the symptoms." },
  prescribe: { translation: "выписывать", pos: "гл.", example: "The doctor prescribed antibiotics." },
  diagnose: { translation: "ставить диагноз", pos: "гл.", example: "Hard to diagnose." },
};

export function vocabularyByGrade(grade: Grade): VocabWord[] {
  const mods = CURRICULUM.filter((m) => m.grade === grade);
  const words: VocabWord[] = [];
  const seen = new Set<string>();
  for (const m of mods) {
    for (const w of m.vocabulary) {
      const meta = TRANSLATIONS[w];
      if (!meta) continue;
      const id = `vw-${grade}-${m.number}-${w.replace(/\s+/g, "_")}`;
      if (seen.has(id)) continue;
      seen.add(id);
      words.push({
        id,
        grade,
        moduleNumber: m.number,
        moduleTitle: m.title,
        word: w,
        translation: meta.translation,
        partOfSpeech: meta.pos,
        example: meta.example,
        transcription: meta.tr,
      });
    }
  }
  return words;
}

export function vocabularyAll(): VocabWord[] {
  const out: VocabWord[] = [];
  for (const grade of [2, 3, 4, 5, 6, 7, 8] as Grade[]) {
    out.push(...vocabularyByGrade(grade));
  }
  return out;
}
