import type { VocabWord, Grade } from "@/types";
import { CURRICULUM } from "@/lib/curriculum";

const TRANSLATIONS: Record<string, { translation: string; pos: string; example: string; tr?: string }> = {
  bedroom: { translation: "спальня", pos: "сущ.", example: "My bedroom is small." },
  kitchen: { translation: "кухня", pos: "сущ.", example: "Mum is in the kitchen." },
  bathroom: { translation: "ванная", pos: "сущ.", example: "The bathroom is upstairs." },
  garden: { translation: "сад", pos: "сущ.", example: "We play in the garden." },
  "dining room": { translation: "столовая", pos: "сущ.", example: "We have dinner in the dining room." },
  cake: { translation: "торт", pos: "сущ.", example: "I like chocolate cake." },
  candles: { translation: "свечи", pos: "сущ.", example: "There are ten candles on the cake." },
  "ice cream": { translation: "мороженое", pos: "сущ.", example: "I want strawberry ice cream." },
  chocolate: { translation: "шоколад", pos: "сущ.", example: "Dark chocolate is bitter." },
  lemonade: { translation: "лимонад", pos: "сущ.", example: "A glass of lemonade, please." },
  fish: { translation: "рыба", pos: "сущ.", example: "I have got a fish." },
  bird: { translation: "птица", pos: "сущ.", example: "The bird can fly." },
  frog: { translation: "лягушка", pos: "сущ.", example: "A frog can jump." },
  horse: { translation: "лошадь", pos: "сущ.", example: "Horses live on the farm." },
  chimp: { translation: "шимпанзе", pos: "сущ.", example: "The chimp is funny." },
  "teddy bear": { translation: "плюшевый мишка", pos: "сущ.", example: "I have a teddy bear." },
  "toy soldier": { translation: "солдатик", pos: "сущ.", example: "A toy soldier is on the shelf." },
  ballerina: { translation: "балерина", pos: "сущ.", example: "The ballerina is dancing." },
  shelf: { translation: "полка", pos: "сущ.", example: "Put the book on the shelf." },
  "musical box": { translation: "музыкальная шкатулка", pos: "сущ.", example: "Open the musical box." },
  Maths: { translation: "математика", pos: "сущ.", example: "Maths is my favourite subject." },
  English: { translation: "английский", pos: "сущ.", example: "We learn English." },
  PE: { translation: "физкультура", pos: "сущ.", example: "We have PE on Monday." },
  Science: { translation: "естествознание", pos: "сущ.", example: "We do experiments in Science." },
  Art: { translation: "рисование", pos: "сущ.", example: "I love Art class." },
  grandma: { translation: "бабушка", pos: "сущ.", example: "My grandma bakes pies." },
  grandpa: { translation: "дедушка", pos: "сущ.", example: "Grandpa tells stories." },
  cousin: { translation: "двоюродный брат/сестра", pos: "сущ.", example: "My cousin is ten." },
  uncle: { translation: "дядя", pos: "сущ.", example: "Uncle Tom is a pilot." },
  aunt: { translation: "тётя", pos: "сущ.", example: "Aunt Mary is kind." },
  pasta: { translation: "паста", pos: "сущ.", example: "I like pasta with cheese." },
  rice: { translation: "рис", pos: "сущ.", example: "Rice with fish is tasty." },
  meat: { translation: "мясо", pos: "сущ.", example: "We eat meat for dinner." },
  vegetables: { translation: "овощи", pos: "сущ.", example: "Vegetables are healthy." },
  doll: { translation: "кукла", pos: "сущ.", example: "She has a new doll." },
  plane: { translation: "самолёт", pos: "сущ.", example: "The plane is flying high." },
  train: { translation: "поезд", pos: "сущ.", example: "The train is fast." },
  "rocking horse": { translation: "лошадка-качалка", pos: "сущ.", example: "The rocking horse is old." },
  tall: { translation: "высокий", pos: "прил.", example: "My dad is tall." },
  short: { translation: "низкий / короткий", pos: "прил.", example: "Her hair is short." },
  funny: { translation: "весёлый", pos: "прил.", example: "A funny cartoon." },
  kind: { translation: "добрый", pos: "прил.", example: "She is very kind." },
  shy: { translation: "застенчивый", pos: "прил.", example: "He is shy with strangers." },
  doctor: { translation: "врач", pos: "сущ.", example: "The doctor helps us." },
  dentist: { translation: "стоматолог", pos: "сущ.", example: "The dentist fixes teeth." },
  farmer: { translation: "фермер", pos: "сущ.", example: "The farmer works on a farm." },
  waiter: { translation: "официант", pos: "сущ.", example: "The waiter is polite." },
  mechanic: { translation: "механик", pos: "сущ.", example: "The mechanic repairs cars." },
  bread: { translation: "хлеб", pos: "сущ.", example: "Bread and butter." },
  butter: { translation: "масло", pos: "сущ.", example: "Spread butter on the bread." },
  cheese: { translation: "сыр", pos: "сущ.", example: "Do you like cheese?" },
  honey: { translation: "мёд", pos: "сущ.", example: "Honey is sweet." },
  lion: { translation: "лев", pos: "сущ.", example: "The lion is strong." },
  elephant: { translation: "слон", pos: "сущ.", example: "An elephant is big." },
  giraffe: { translation: "жираф", pos: "сущ.", example: "The giraffe is tall." },
  peacock: { translation: "павлин", pos: "сущ.", example: "A peacock has a beautiful tail." },
  seal: { translation: "тюлень", pos: "сущ.", example: "The seal is swimming." },
  timetable: { translation: "расписание", pos: "сущ.", example: "Look at the timetable." },
  schoolbag: { translation: "портфель", pos: "сущ.", example: "My schoolbag is heavy." },
  pupil: { translation: "ученик", pos: "сущ.", example: "He is a good pupil." },
  headmaster: { translation: "директор школы", pos: "сущ.", example: "The headmaster is in his office." },
  subject: { translation: "предмет", pos: "сущ.", example: "History is my favourite subject." },
  Russia: { translation: "Россия", pos: "сущ.", example: "I live in Russia." },
  Britain: { translation: "Британия", pos: "сущ.", example: "London is in Britain." },
  Spain: { translation: "Испания", pos: "сущ.", example: "Spain is sunny." },
  passport: { translation: "паспорт", pos: "сущ.", example: "I need my passport." },
  nationality: { translation: "национальность", pos: "сущ.", example: "What nationality are you?" },
  armchair: { translation: "кресло", pos: "сущ.", example: "Sit in the armchair." },
  carpet: { translation: "ковёр", pos: "сущ.", example: "The carpet is red." },
  fridge: { translation: "холодильник", pos: "сущ.", example: "Milk is in the fridge." },
  mirror: { translation: "зеркало", pos: "сущ.", example: "Look at the mirror." },
  wardrobe: { translation: "шкаф", pos: "сущ.", example: "Put your coat in the wardrobe." },
  brave: { translation: "смелый", pos: "прил.", example: "A brave soldier." },
  clever: { translation: "умный", pos: "прил.", example: "She is a clever girl." },
  noisy: { translation: "шумный", pos: "прил.", example: "A noisy street." },
  patient: { translation: "терпеливый", pos: "прил.", example: "Teachers must be patient." },
  "ID card": { translation: "удостоверение", pos: "сущ.", example: "Show me your ID card." },
  nickname: { translation: "прозвище", pos: "сущ.", example: "My nickname is Tiger." },
  address: { translation: "адрес", pos: "сущ.", example: "Write your address." },
  postcode: { translation: "индекс", pos: "сущ.", example: "The postcode is 101000." },
  signature: { translation: "подпись", pos: "сущ.", example: "Put your signature here." },
  calendar: { translation: "календарь", pos: "сущ.", example: "Mark the day on the calendar." },
  celebration: { translation: "праздник", pos: "сущ.", example: "A big celebration." },
  month: { translation: "месяц", pos: "сущ.", example: "July is a hot month." },
  season: { translation: "время года", pos: "сущ.", example: "Winter is a cold season." },
  festival: { translation: "фестиваль", pos: "сущ.", example: "The festival is in summer." },
  bicycle: { translation: "велосипед", pos: "сущ.", example: "I ride my bicycle to school." },
  underground: { translation: "метро", pos: "сущ.", example: "Take the underground." },
  helicopter: { translation: "вертолёт", pos: "сущ.", example: "A helicopter is flying." },
  tram: { translation: "трамвай", pos: "сущ.", example: "The tram is yellow." },
  motorbike: { translation: "мотоцикл", pos: "сущ.", example: "Dad has a motorbike." },
  routine: { translation: "распорядок", pos: "сущ.", example: "My daily routine." },
  "spare time": { translation: "свободное время", pos: "сущ.", example: "In my spare time I read." },
  hobby: { translation: "хобби", pos: "сущ.", example: "Music is my hobby." },
  weekend: { translation: "выходные", pos: "сущ.", example: "On the weekend I sleep in." },
  habit: { translation: "привычка", pos: "сущ.", example: "Reading is a good habit." },
  countryside: { translation: "сельская местность", pos: "сущ.", example: "We go to the countryside in summer." },
  suburbs: { translation: "пригород", pos: "сущ.", example: "They live in the suburbs." },
  skyscraper: { translation: "небоскрёб", pos: "сущ.", example: "The skyscraper is 50 floors high." },
  cottage: { translation: "коттедж", pos: "сущ.", example: "A lovely little cottage." },
  flat: { translation: "квартира", pos: "сущ.", example: "We live in a flat." },
  character: { translation: "персонаж", pos: "сущ.", example: "The main character is brave." },
  plot: { translation: "сюжет", pos: "сущ.", example: "The plot is exciting." },
  hero: { translation: "герой", pos: "сущ.", example: "He is the hero of the story." },
  villain: { translation: "злодей", pos: "сущ.", example: "The villain is clever." },
  adventure: { translation: "приключение", pos: "сущ.", example: "A great adventure begins." },
  ambitious: { translation: "амбициозный", pos: "прил.", example: "An ambitious student." },
  creative: { translation: "творческий", pos: "прил.", example: "A creative mind." },
  loyal: { translation: "преданный", pos: "прил.", example: "A loyal friend." },
  generous: { translation: "щедрый", pos: "прил.", example: "A generous heart." },
  headline: { translation: "заголовок", pos: "сущ.", example: "Read the headline." },
  broadcast: { translation: "трансляция", pos: "сущ.", example: "Live broadcast from the stadium." },
  journalist: { translation: "журналист", pos: "сущ.", example: "She is a journalist." },
  report: { translation: "репортаж", pos: "сущ.", example: "Write a short report." },
  article: { translation: "статья", pos: "сущ.", example: "A newspaper article." },
  polite: { translation: "вежливый", pos: "прил.", example: "Be polite to elders." },
  rude: { translation: "грубый", pos: "прил.", example: "Don't be rude." },
  sociable: { translation: "общительный", pos: "прил.", example: "She is very sociable." },
  outgoing: { translation: "открытый", pos: "прил.", example: "He is outgoing and friendly." },
  introvert: { translation: "интроверт", pos: "сущ.", example: "I'm more of an introvert." },
  receipt: { translation: "чек", pos: "сущ.", example: "Keep your receipt." },
  discount: { translation: "скидка", pos: "сущ.", example: "A 20% discount." },
  refund: { translation: "возврат", pos: "сущ.", example: "I got a refund." },
  grocery: { translation: "продуктовый магазин", pos: "сущ.", example: "I go to the grocery." },
  boutique: { translation: "бутик", pos: "сущ.", example: "A small boutique." },
  invention: { translation: "изобретение", pos: "сущ.", example: "A great invention." },
  discover: { translation: "открывать", pos: "гл.", example: "Columbus discovered America." },
  genius: { translation: "гений", pos: "сущ.", example: "Einstein was a genius." },
  breakthrough: { translation: "прорыв", pos: "сущ.", example: "A scientific breakthrough." },
  experiment: { translation: "эксперимент", pos: "сущ.", example: "Conduct an experiment." },
  outfit: { translation: "наряд", pos: "сущ.", example: "A cool outfit." },
  trendy: { translation: "модный", pos: "прил.", example: "Trendy sneakers." },
  baggy: { translation: "мешковатый", pos: "прил.", example: "Baggy jeans." },
  tight: { translation: "тесный", pos: "прил.", example: "Tight shoes hurt." },
  formal: { translation: "официальный", pos: "прил.", example: "A formal suit." },
};

export function vocabularyByGrade(grade: Grade): VocabWord[] {
  const mods = CURRICULUM.filter((m) => m.grade === grade);
  const words: VocabWord[] = [];
  for (const m of mods) {
    for (const w of m.vocabulary) {
      const meta = TRANSLATIONS[w];
      if (!meta) continue;
      words.push({
        id: `vw-${grade}-${m.number}-${w.replace(/\s+/g, "_")}`,
        grade,
        word: w,
        translation: meta.translation,
        partOfSpeech: meta.pos,
        example: meta.example,
        transcription: meta.tr,
      });
    }
  }
  return words;
}
